################################################################################
#
# dolphin-triforce
#
################################################################################
# Version: Commits on May 23, 2024
DOLPHIN_TRIFORCE_VERSION = bfefd38d2500103d32f5da9f7fcd80090b7836fb
DOLPHIN_TRIFORCE_BRANCH = crediar
DOLPHIN_TRIFORCE_SITE = https://github.com/Hancock33/dolphin-triforce.git
DOLPHIN_TRIFORCE_SITE_METHOD = git
DOLPHIN_TRIFORCE_LICENSE = GPLv2+
DOLPHIN_TRIFORCE_GIT_SUBMODULES = YES
DOLPHIN_TRIFORCE_SUPPORTS_IN_SOURCE_BUILD = NO

DOLPHIN_TRIFORCE_DEPENDENCIES = libevdev ffmpeg zlib libpng lzo libusb libcurl
DOLPHIN_TRIFORCE_DEPENDENCIES += bluez5_utils hidapi xz host-xz sdl2
DOLPHIN_TRIFORCE_DEPENDENCIES += qt6base qt6svg

DOLPHIN_TRIFORCE_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
DOLPHIN_TRIFORCE_CONF_OPTS += -DDISTRIBUTOR='batocera.linux'
DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_ANALYTICS=OFF
DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_AUTOUPDATE=OFF
DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_CLI_TOOL=OFF
DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_LLVM=OFF
DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_TESTS=OFF
DOLPHIN_TRIFORCE_CONF_OPTS += -DUSE_DISCORD_PRESENCE=OFF
DOLPHIN_TRIFORCE_CONF_OPTS += -DUSE_MGBA=OFF
DOLPHIN_TRIFORCE_CONF_OPTS += -DUSE_UPNP=OFF
DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_QT=ON
DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_NOGUI=OFF

ifeq ($(BR2_PACKAGE_XORG7),y)
	DOLPHIN_EMU_DEPENDENCIES += xserver_xorg-server
	DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_X11=ON
else
	DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_X11=OFF
endif

ifeq ($(BR2_PACKAGE_VULKAN_HEADERS)$(BR2_PACKAGE_VULKAN_LOADER),yy)
	DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_VULKAN=ON
else
	DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_VULKAN=OFF
endif

define DOLPHIN_TRIFORCE_INSTALL_TARGET_CMDS
	cp $(@D)/buildroot-build/Binaries/dolphin-emu $(TARGET_DIR)/usr/bin/dolphin-triforce
	mkdir -p $(TARGET_DIR)/usr/share/evmapy
	cp $(BR2_EXTERNAL_BATOCERA_PATH)/package/batocera/emulators/dolphin-triforce/*.keys $(TARGET_DIR)/usr/share/evmapy
endef

$(eval $(cmake-package))
