################################################################################
#
# dolphin-triforce
#
################################################################################
# Version: Commits on Aug 15, 2025
DOLPHIN_TRIFORCE_VERSION = 842a088dcecbc99348b24557396f56456ceaf2ac
DOLPHIN_TRIFORCE_BRANCH = new
DOLPHIN_TRIFORCE_SITE = https://github.com/Hancock33/dolphin-triforce.git
DOLPHIN_TRIFORCE_SITE_METHOD = git
DOLPHIN_TRIFORCE_LICENSE = GPLv2+
DOLPHIN_TRIFORCE_GIT_SUBMODULES = YES
DOLPHIN_TRIFORCE_SUPPORTS_IN_SOURCE_BUILD = NO

DOLPHIN_TRIFORCE_DEPENDENCIES += bluez5_utils ffmpeg hidapi host-xz libcurl libevdev libpng libusb lzo sdl2 speex xz zlib

DOLPHIN_TRIFORCE_CONF_OPTS += -DCMAKE_CXX_FLAGS="$(TARGET_CFLAGS) -DFMT_CONSTEVAL="
DOLPHIN_TRIFORCE_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
DOLPHIN_TRIFORCE_CONF_OPTS += -DDISTRIBUTOR='batocera.linux'
DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_ANALYTICS=OFF
DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_AUTOUPDATE=OFF
DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_CLI_TOOL=OFF
DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_LTO=ON
DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_TESTS=OFF
DOLPHIN_TRIFORCE_CONF_OPTS += -DUSE_DISCORD_PRESENCE=OFF
DOLPHIN_TRIFORCE_CONF_OPTS += -DUSE_MGBA=OFF
DOLPHIN_TRIFORCE_CONF_OPTS += -DUSE_UPNP=OFF

ifeq ($(BR2_PACKAGE_QT6),y)
    DOLPHIN_EMU_DEPENDENCIES += qt6base qt6svg
    DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_QT=ON
    DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_NOGUI=ON
else
    DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_QT=OFF
    DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_NOGUI=ON
endif

ifeq ($(BR2_PACKAGE_XORG7),y)
    DOLPHIN_EMU_DEPENDENCIES += xserver_xorg-server
    DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_X11=ON
else
    DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_X11=OFF
endif

ifeq ($(BR2_PACKAGE_BATOCERA_VULKAN),y)
    DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_VULKAN=ON
else
    DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_VULKAN=OFF
endif

define DOLPHIN_TRIFORCE_EXTRAS
	mkdir -p $(TARGET_DIR)/usr/share/triforce
	# copy extra ini files
	cp -prn $(BR2_EXTERNAL_BATOCERA_PATH)/package/batocera/emulators/dolphin-triforce/*.ini $(TARGET_DIR)/usr/share/triforce
	# copy evmapy files
	mkdir -p $(TARGET_DIR)/usr/share/evmapy
	cp -prn $(BR2_EXTERNAL_BATOCERA_PATH)/package/batocera/emulators/dolphin-triforce/*.keys $(TARGET_DIR)/usr/share/evmapy
endef

DOLPHIN_TRIFORCE_POST_INSTALL_TARGET_HOOKS += DOLPHIN_TRIFORCE_EXTRAS

$(eval $(cmake-package))
