################################################################################
#
# dolphin-triforce
#
################################################################################
# Version: Commits on Dec 30, 2024
DOLPHIN_TRIFORCE_VERSION = cc15858c4aacaca7ca7b346afd0752b909b63064
DOLPHIN_TRIFORCE_BRANCH = new
DOLPHIN_TRIFORCE_SITE = https://github.com/Hancock33/dolphin-triforce.git
DOLPHIN_TRIFORCE_SITE_METHOD = git
DOLPHIN_TRIFORCE_LICENSE = GPLv2+
DOLPHIN_TRIFORCE_GIT_SUBMODULES = YES
DOLPHIN_TRIFORCE_SUPPORTS_IN_SOURCE_BUILD = NO

DOLPHIN_TRIFORCE_DEPENDENCIES += bluez5_utils ffmpeg hidapi host-xz libcurl libevdev libpng libusb lzo sdl2 speex xz zlib

ifeq ($(BR2_PACKAGE_QT6),y)
DOLPHIN_TRIFORCE_DEPENDENCIES += qt6base qt6svg
endif

DOLPHIN_TRIFORCE_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
DOLPHIN_TRIFORCE_CONF_OPTS += -DDISTRIBUTOR='batocera.linux'
DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_ANALYTICS=OFF
DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_AUTOUPDATE=OFF
DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_CLI_TOOL=OFF
DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_LLVM=OFF
DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_TESTS=OFF
DOLPHIN_TRIFORCE_CONF_OPTS += -DUSE_DISCORD_PRESENCE=OFF
DOLPHIN_TRIFORCE_CONF_OPTS += -DUSE_MGBA=OFF
DOLPHIN_TRIFORCE_CONF_OPTS += -DUSE_UPNP=OFF
DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_QT=ON
DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_NOGUI=OFF

ifeq ($(BR2_PACKAGE_XORG7),y)
    DOLPHIN_EMU_DEPENDENCIES += xserver_xorg-server
    DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_X11=ON
else
    DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_X11=OFF
endif

ifeq ($(BR2_PACKAGE_BATOCERA_VULKAN),y)
    DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_VULKAN=ON
else
    DOLPHIN_TRIFORCE_CONF_OPTS += -DENABLE_VULKAN=OFF
endif

define DOLPHIN_TRIFORCE_EXTRAS
	mkdir -p $(TARGET_DIR)/usr/share/triforce
	# copy extra ini files
	cp -prn $(BR2_EXTERNAL_BATOCERA_PATH)/package/batocera/emulators/dolphin-triforce/*.ini $(TARGET_DIR)/usr/share/triforce
endef

DOLPHIN_TRIFORCE_POST_INSTALL_TARGET_HOOKS += DOLPHIN_TRIFORCE_EXTRAS

$(eval $(cmake-package))
