################################################################################
#
# duckstation-legacy
#
################################################################################
# Version: Commits on Aug 4, 2023 - DON'T BUMP
DUCKSTATION_LEGACY_VERSION = 56ac3d6c324ec4520dac433b071ecab6227fb459
DUCKSTATION_LEGACY_SITE = $(call github,stenzek,duckstation,$(DUCKSTATION_LEGACY_VERSION))
DUCKSTATION_LEGACY_LICENSE = GPLv2
DUCKSTATION_LEGACY_DEPENDENCIES = fmt boost ffmpeg libcurl ecm dbus

DUCKSTATION_LEGACY_SUPPORTS_IN_SOURCE_BUILD = NO

DUCKSTATION_LEGACY_CONF_OPTS += -DBUILD_SHARED_LIBS=FALSE
DUCKSTATION_LEGACY_CONF_OPTS += -DENABLE_DISCORD_PRESENCE=OFF
DUCKSTATION_LEGACY_CONF_OPTS += -DBUILD_QT_FRONTEND=OFF
DUCKSTATION_LEGACY_CONF_OPTS += -DBUILD_NOGUI_FRONTEND=ON
DUCKSTATION_LEGACY_CONF_OPTS += -DUSE_DRMKMS=ON

DUCKSTATION_LEGACY_CONF_ENV += LDFLAGS=-lpthread

ifeq ($(BR2_PACKAGE_WAYLAND),y)
    DUCKSTATION_LEGACY_CONF_OPTS += -DUSE_WAYLAND=ON
else
    DUCKSTATION_LEGACY_CONF_OPTS += -DUSE_WAYLAND=OFF
endif

ifeq ($(BR2_PACKAGE_XORG7),y)
    DUCKSTATION_LEGACY_CONF_OPTS += -DUSE_X11=ON
else
    DUCKSTATION_LEGACY_CONF_OPTS += -DUSE_X11=OFF
endif

ifeq ($(BR2_PACKAGE_VULKAN_HEADERS)$(BR2_PACKAGE_VULKAN_LOADER),yy)
    DUCKSTATION_LEGACY_CONF_OPTS += -DENABLE_VULKAN=ON
else
    DUCKSTATION_LEGACY_CONF_OPTS += -DENABLE_VULKAN=OFF
endif

ifeq ($(BR2_PACKAGE_XORG7),y)
    DUCKSTATION_LEGACY_CONF_OPTS += -DUSE_GLX=ON
endif

ifeq ($(BR2_PACKAGE_HAS_LIBEGL),y)
    DUCKSTATION_LEGACY_CONF_OPTS += -DUSE_EGL=ON
    ifeq ($(BR2_PACKAGE_HAS_LIBMALI),y)
        DUCKSTATION_LEGACY_CONF_OPTS += -DUSE_MALI=ON
    endif
else
    DUCKSTATION_LEGACY_CONF_OPTS += -DUSE_EGL=OFF
endif

define DUCKSTATION_LEGACY_INSTALL_TARGET_CMDS
	rm -rf $(TARGET_DIR)/usr/bin/duckstation-legacy
	cp -R $(@D)/buildroot-build/bin $(TARGET_DIR)/usr/bin/duckstation-legacy
endef

$(eval $(cmake-package))
