################################################################################
#
# libretro-flycast
#
################################################################################
# Version: Commits on Aug 17, 2025
LIBRETRO_FLYCAST_VERSION = d3dcb13ef95b5c30fcc9d009b2c52eb5a8883ff6
LIBRETRO_FLYCAST_SOURCE = flycast-$(LIBRETRO_FLYCAST_VERSION)-git4.tar.gz
LIBRETRO_FLYCAST_SITE = https://github.com/flyinghead/flycast.git
LIBRETRO_FLYCAST_SITE_METHOD=git
LIBRETRO_FLYCAST_GIT_SUBMODULES=YES
LIBRETRO_FLYCAST_SUPPORTS_IN_SOURCE_BUILD = NO
LIBRETRO_FLYCAST_LICENSE = GPLv2
LIBRETRO_FLYCAST_DEPENDENCIES = retroarch

LIBRETRO_FLYCAST_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
LIBRETRO_FLYCAST_CONF_OPTS += -DLIBRETRO=ON
LIBRETRO_FLYCAST_CONF_OPTS += -DUSE_OPENMP=ON
LIBRETRO_FLYCAST_CONF_OPTS += -DBUILD_EXTERNAL=OFF

# OpenGL backend
ifeq ($(BR2_PACKAGE_HAS_LIBGL),y)
    LIBRETRO_FLYCAST_DEPENDENCIES += libgl
    LIBRETRO_FLYCAST_CONF_OPTS += -DUSE_OPENGL=ON
else ifeq ($(BR2_PACKAGE_BATOCERA_GLES3),y)
    LIBRETRO_FLYCAST_DEPENDENCIES += libgles
    LIBRETRO_FLYCAST_CONF_OPTS += -DUSE_GLES=ON -DUSE_GLES2=OFF
else ifeq ($(BR2_PACKAGE_BATOCERA_GLES2),y)
    LIBRETRO_FLYCAST_DEPENDENCIES += libgles
    LIBRETRO_FLYCAST_CONF_OPTS += -DUSE_GLES2=ON -DUSE_GLES=OFF
endif

# Vulkan backend
ifeq ($(BR2_PACKAGE_BATOCERA_VULKAN),y)
    LIBRETRO_FLYCAST_CONF_OPTS += -DUSE_VULKAN=ON -DUSE_HOST_GLSLANG=ON
else
    LIBRETRO_FLYCAST_CONF_OPTS += -DUSE_VULKAN=OFF
endif

define LIBRETRO_FLYCAST_INSTALL_TARGET_CMDS
	mkdir -p $(TARGET_DIR)/usr/lib/libretro
	$(INSTALL) -D $(@D)/buildroot-build/flycast_libretro.so $(TARGET_DIR)/usr/lib/libretro/flycast_libretro.so
endef

define LIBRETRO_FLYCAST_GET_SUBMODULE
	rm -rf $(@D)/core/deps/glslang
endef
LIBRETRO_FLYCAST_POST_EXTRACT_HOOKS = LIBRETRO_FLYCAST_GET_SUBMODULE

$(eval $(cmake-package))
