################################################################################
#
# libretro-flycast
#
################################################################################
# Version: Commits on May 02, 2025
LIBRETRO_FLYCAST_VERSION = c57b2e1aa775c21f6ddcd090607f4b3ba1a1baa1
LIBRETRO_FLYCAST_SOURCE = flycast-$(LIBRETRO_FLYCAST_VERSION)-git4.tar.gz
LIBRETRO_FLYCAST_SITE = https://github.com/flyinghead/flycast.git
LIBRETRO_FLYCAST_SITE_METHOD=git
LIBRETRO_FLYCAST_GIT_SUBMODULES=YES
LIBRETRO_FLYCAST_SUPPORTS_IN_SOURCE_BUILD = NO
LIBRETRO_FLYCAST_LICENSE = GPLv2
LIBRETRO_FLYCAST_DEPENDENCIES = retroarch

LIBRETRO_FLYCAST_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
LIBRETRO_FLYCAST_CONF_OPTS += -DLIBRETRO=ON
LIBRETRO_FLYCAST_CONF_OPTS += -DUSE_HOST_SDL=ON

# Get version details
LIBRETRO_FLYCAST_GIT_TAG =  $(shell git -C $(LIBRETRO_FLYCAST_DL_DIR)/git describe --tags --always | tr -d '\n')
LIBRETRO_FLYCAST_GIT_HASH = $(shell git -C $(LIBRETRO_FLYCAST_DL_DIR)/git rev-parse --short HEAD | tr -d '\n')
LIBRETRO_FLYCAST_CONF_OPTS += -DGIT_VERSION=$(LIBRETRO_FLYCAST_GIT_TAG)
LIBRETRO_FLYCAST_CONF_OPTS += -DGIT_HASH=$(LIBRETRO_FLYCAST_GIT_HASH)

ifeq ($(BR2_PACKAGE_BATOCERA_GLES3),y)
    LIBRETRO_FLYCAST_CONF_OPTS += -DUSE_GLES=ON
else ifeq ($(BR2_PACKAGE_BATOCERA_GLES2),y)
    LIBRETRO_FLYCAST_CONF_OPTS += -DUSE_GLES2=ON
endif

ifeq ($(BR2_PACKAGE_BATOCERA_VULKAN),)
    LIBRETRO_FLYCAST_CONF_OPTS += -DUSE_VULKAN=OFF
endif

ifeq ($(BR2_PACKAGE_HAS_LIBMALI),y)
    LIBRETRO_FLYCAST_DEPENDENCIES += libmali
    LIBRETRO_FLYCAST_CONF_OPTS += -DUSE_MALI=ON
endif

ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_RK3399),y)
    LIBRETRO_FLYCAST_CONF_OPTS += -DRK3399=ON
else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_BCM2711),y)
    LIBRETRO_FLYCAST_CONF_OPTS += -DRPI4=ON
else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_BCM2712),y)
    LIBRETRO_FLYCAST_CONF_OPTS += -DRPI5=ON
else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_XU4),y)
    LIBRETRO_FLYCAST_CONF_OPTS += -DODROIDXU4=ON
else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_S922X),y)
    LIBRETRO_FLYCAST_CONF_OPTS += -DS922X=ON
endif

define LIBRETRO_FLYCAST_INSTALL_TARGET_CMDS
	mkdir -p $(TARGET_DIR)/usr/lib/libretro
	$(INSTALL) -D $(@D)/buildroot-build/flycast_libretro.so $(TARGET_DIR)/usr/lib/libretro/flycast_libretro.so
endef

$(eval $(cmake-package))
