#!/usr/bin/env python
import batoceraFiles
import Command
import controllersConfig
from generators.Generator import Generator
import os
from os import path

class LzdoomGenerator(Generator):
    def generate(self, system, rom, playersControllers, guns, gameResolution):
        config_dir = f"{batoceraFiles.CONF}/lzdoom"
        if not os.path.exists(config_dir):
            os.mkdir(config_dir)

        extra_config = 'bind ] weapnext\n'

        if system.isOptSet('lzdoom_render'):
            if system.config['lzdoom_render'] == 'soft':
                extra_config += (
                    # Use the Software render:
                    'vid_rendermode 0\n'
                )
            if system.config['lzdoom_render'] == 'gl':
                extra_config += (
                    # Use the OpenGL render:
                    'vid_rendermode 1\n'
                )
        else:
            extra_config += (
                # Use the Software render:
                'vid_rendermode 0\n'
                )

        iwad = ''
        pwad = ''

        if (rom.__contains__('.uwad')):
            f=open(rom)
            content=f.readlines()
            for line in content:
                if 'IWAD=/' in line:
                    iwad = line.replace('IWAD=', '').replace('\n', '')
                elif 'PWAD=/' in line:
                    pwad = line.replace('PWAD=', '').replace('\n', '')
        else:
                    iwad = rom

        # A script file with console commands that are always ran when a game starts
        script_file = f"{config_dir}/lzdoom.cfg"
        with open(script_file, "w") as script:
            script.write(
                "# This file is automatically generated by lzdoomGenerator.py\n"
                # In the code, logfile does not appear to be created unless done so explicitly
                f"logfile {batoceraFiles.logdir}/lzdoom.log\n"
                f"vid_fps {'true' if system.getOptBoolean('showFPS') else 'false'}\n"
                f"{extra_config}"
                "echo BATOCERA\n"  # easy check that script ran in console
            )

        return Command.Command(
            array=[
                '/usr/share/lzdoom/lzdoom',
                '-iwad', iwad,
                '-file', pwad,
                '-exec', script_file,
                # Disable controllers because support is poor; use evmapy instead
                '-nojoy',
                '-fullscreen',
                '-width', str(gameResolution['width']),
                '-height', str(gameResolution['height']),
            ],
            env={
                'DOOMWADDIR': '/userdata/roms/ports/doom',
                'SDL_AUTO_UPDATE_JOYSTICKS': '0'
            }
        )