## MEGA-BEZEL
default:
  # shader affects retroarch shaders
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
  # scanline affect fba2x
  scanline: true
snes:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
nes:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
n64:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
gba:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE__LCD-GRID
gb:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE__LCD-GRID
gbc:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE__LCD-GRID
pokemini:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE__LCD-GRID
fds:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
virtualboy:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE__LCD-GRID
nds:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__NDS__ULTRALITE
3ds:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__3DS__ULTRALITE
# Sega
sg1000:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
mastersystem:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
megadrive:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
gamegear:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE__LCD-GRID
sega32x:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
segacd:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
# Arcade
neogeo:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
neogeocd:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
mame:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
fba:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
naomi:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
atomiswave:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
#
ngp:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE__LCD-GRID
ngpc:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE__LCD-GRID
gw:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
vectrex:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
lynx:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE__LCD-GRID
lutro:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
wswan:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE__LCD-GRID
wswanc:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE__LCD-GRID
pcengine:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
pcenginecd:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
supergrafx:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
atari800:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
atari2600:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
atari5200:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
atari7800:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
prboom:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
psx:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
psp:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE__LCD-GRID
colecovision:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
# Computers
msx:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
msx1:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
msx2:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
amiga:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
amstradcpc:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
atarist:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
zxspectrum:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
odyssey2:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
zx81:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
pcfx:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
x68000:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__ULTRALITE
