################################################################################
#
# vpinball-common
#
################################################################################

VPINBALL_COMMON_VERSION = 1.0
VPINBALL_COMMON_CONF_OPTS += -DPLATFORM=linux
VPINBALL_COMMON_CONF_OPTS += -DPOST_BUILD_COPY_EXT_LIBS=OFF
VPINBALL_COMMON_CONF_OPTS += -DBUILD_STATIC=OFF

# handle supported target platforms
ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_RK3588),y)
    VPINBALL_COMMON_CONF_OPTS += -DARCH=aarch64
    VPINBALL_COMMON_CONF_OPTS += -DBUILD_RK3588=ON
    VPINBALL_COMMON_ARCH = aarch64
    VPINBALL_COMMON_BASS = aarch64
endif

ifeq ($(BR2_PACKAGE_BATOCERA_BCM27XX),y)
    VPINBALL_COMMON_CONF_OPTS += -DARCH=aarch64
    VPINBALL_COMMON_CONF_OPTS += -DBUILD_RPI=ON
    VPINBALL_COMMON_ARCH = aarch64
    VPINBALL_COMMON_BASS = aarch64
endif

ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_X86_64_ANY),y)
    VPINBALL_COMMON_CONF_OPTS += -DARCH=x64
    VPINBALL_COMMON_ARCH = x64
    VPINBALL_COMMON_BASS = x86_64
endif

VPINBALL_COMMON_CMAKE = CMakeLists_gl-linux-$(VPINBALL_COMMON_ARCH).txt
VPINBALL_COMMON_SRC = linux-$(VPINBALL_COMMON_ARCH)
