################################################################################
#
# dolphin-emu
#
################################################################################
# Version: Commits on May 21, 2024
DOLPHIN_EMU_VERSION = 321dc9b76deff1dc3053dd26d1b5f5248bbdc206
DOLPHIN_EMU_SITE = https://github.com/dolphin-emu/dolphin
DOLPHIN_EMU_SITE_METHOD = git
DOLPHIN_EMU_LICENSE = GPLv2+
DOLPHIN_EMU_GIT_SUBMODULES = YES
DOLPHIN_EMU_SUPPORTS_IN_SOURCE_BUILD = NO

DOLPHIN_EMU_DEPENDENCIES = libevdev ffmpeg zlib libpng lzo libusb libcurl
DOLPHIN_EMU_DEPENDENCIES += bluez5_utils hidapi xz host-xz sdl2

DOLPHIN_EMU_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
DOLPHIN_EMU_CONF_OPTS += -DDISTRIBUTOR='batocera.linux'
DOLPHIN_EMU_CONF_OPTS += -DENABLE_ANALYTICS=OFF
DOLPHIN_EMU_CONF_OPTS += -DENABLE_AUTOUPDATE=OFF
DOLPHIN_EMU_CONF_OPTS += -DENABLE_CLI_TOOL=OFF
DOLPHIN_EMU_CONF_OPTS += -DENABLE_LLVM=OFF
DOLPHIN_EMU_CONF_OPTS += -DENABLE_TESTS=OFF
DOLPHIN_EMU_CONF_OPTS += -DUSE_DISCORD_PRESENCE=OFF
DOLPHIN_EMU_CONF_OPTS += -DUSE_MGBA=OFF
DOLPHIN_EMU_CONF_OPTS += -DUSE_SYSTEM_LIBS=AUTO
DOLPHIN_EMU_CONF_OPTS += -DUSE_UPNP=OFF

ifeq ($(BR2_PACKAGE_QT6),y)
	DOLPHIN_EMU_DEPENDENCIES += qt6base qt6svg
	DOLPHIN_EMU_CONF_OPTS += -DENABLE_QT=ON
	DOLPHIN_EMU_CONF_OPTS += -DENABLE_NOGUI=ON
else
	DOLPHIN_EMU_CONF_OPTS += -DENABLE_QT=OFF
	DOLPHIN_EMU_CONF_OPTS += -DENABLE_NOGUI=ON
endif

ifeq ($(BR2_PACKAGE_XORG7),y)
	DOLPHIN_EMU_CONF_OPTS += -DENABLE_X11=ON
else
	DOLPHIN_EMU_CONF_OPTS += -DENABLE_X11=OFF
endif

ifeq ($(BR2_PACKAGE_VULKAN_HEADERS)$(BR2_PACKAGE_VULKAN_LOADER),yy)
	DOLPHIN_EMU_CONF_OPTS += -DENABLE_VULKAN=ON
else
	DOLPHIN_EMU_CONF_OPTS += -DENABLE_VULKAN=OFF
endif

define DOLPHIN_EMU_EVMAPY
	mkdir -p $(TARGET_DIR)/usr/share/evmapy
	cp $(BR2_EXTERNAL_BATOCERA_PATH)/package/batocera/emulators/dolphin-emu/*.keys $(TARGET_DIR)/usr/share/evmapy
endef

DOLPHIN_EMU_POST_INSTALL_TARGET_HOOKS = DOLPHIN_EMU_EVMAPY

$(eval $(cmake-package))
