################################################################################
#
# dolphin-emu
#
################################################################################
# Version: Commits on Jan 31, 2026
DOLPHIN_EMU_VERSION = 6711d77b9901ed0a4418203db49ed4d8576e6fe0
DOLPHIN_EMU_VERSION_MAJOR = 2512
DOLPHIN_EMU_VERSION_MINOR = 263
DOLPHIN_EMU_SITE = https://github.com/dolphin-emu/dolphin
DOLPHIN_EMU_SITE_METHOD = git
DOLPHIN_EMU_LICENSE = GPLv2+
DOLPHIN_EMU_GIT_SUBMODULES = YES
DOLPHIN_EMU_SUPPORTS_IN_SOURCE_BUILD = NO

DOLPHIN_EMU_DEPENDENCIES += bluez5_utils cpp-ipc ffmpeg hidapi host-xz libcurl libevdev libpng libusb lzo sdl3 xz zlib
# add dolphin-triforce as a dependency so it builds first
ifeq ($(BR2_PACKAGE_DOLPHIN_TRIFORCE),y)
    DOLPHIN_EMU_DEPENDENCIES += dolphin-triforce
endif

$(eval $(call register,dolphin.emulator.yml))
$(eval $(call register-if-kconfig,BR2_PACKAGE_BATOCERA_VULKAN,gfxbackend.dolphin.emulator.yml))

DOLPHIN_EMU_MAKE_ENV += LDFLAGS="-Wl,--copy-dt-needed-entries"
DOLPHIN_EMU_CONF_ENV += LDFLAGS="-Wl,--copy-dt-needed-entries"
DOLPHIN_EMU_CONF_OPTS += -DCMAKE_C_FLAGS="$(TARGET_CFLAGS) -flto"
DOLPHIN_EMU_CONF_OPTS += -DCMAKE_CXX_FLAGS="$(TARGET_CXXFLAGS) -flto"
DOLPHIN_EMU_CONF_OPTS += -DCMAKE_EXE_LINKER_FLAGS="-lstdc++ -flto"

DOLPHIN_EMU_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
DOLPHIN_EMU_CONF_OPTS += -DDISTRIBUTOR='batocera.linux'
DOLPHIN_EMU_CONF_OPTS += -DENABLE_ANALYTICS=OFF
DOLPHIN_EMU_CONF_OPTS += -DENABLE_AUTOUPDATE=OFF
DOLPHIN_EMU_CONF_OPTS += -DENABLE_CLI_TOOL=OFF
DOLPHIN_EMU_CONF_OPTS += -DENABLE_LTO=ON
DOLPHIN_EMU_CONF_OPTS += -DENABLE_TESTS=OFF
DOLPHIN_EMU_CONF_OPTS += -DUSE_DISCORD_PRESENCE=OFF
DOLPHIN_EMU_CONF_OPTS += -DUSE_MGBA=ON
DOLPHIN_EMU_CONF_OPTS += -DUSE_RETRO_ACHIEVEMENTS=ON
DOLPHIN_EMU_CONF_OPTS += -DUSE_UPNP=OFF

ifeq ($(BR2_PACKAGE_QT6),y)
    DOLPHIN_EMU_DEPENDENCIES += qt6base qt6svg
    DOLPHIN_EMU_CONF_OPTS += -DENABLE_QT=ON
    DOLPHIN_EMU_CONF_OPTS += -DENABLE_NOGUI=ON
else
    DOLPHIN_EMU_CONF_OPTS += -DENABLE_QT=OFF
    DOLPHIN_EMU_CONF_OPTS += -DENABLE_NOGUI=ON
endif

ifeq ($(BR2_PACKAGE_XORG7),y)
    DOLPHIN_EMU_CONF_OPTS += -DENABLE_X11=ON
else
    DOLPHIN_EMU_CONF_OPTS += -DENABLE_X11=OFF
endif

ifeq ($(BR2_PACKAGE_BATOCERA_VULKAN),y)
    DOLPHIN_EMU_CONF_OPTS += -DENABLE_VULKAN=ON
else
    DOLPHIN_EMU_CONF_OPTS += -DENABLE_VULKAN=OFF
endif

define DOLPHIN_EMU_PRE_CONFIGURE_HOOK
	sed -i 's/set(DOLPHIN_VERSION_MAJOR .*)/set(DOLPHIN_VERSION_MAJOR "$(DOLPHIN_EMU_VERSION_MAJOR)")/' $(@D)/CMake/ScmRevGen.cmake
	sed -i 's/set(DOLPHIN_VERSION_MINOR .*)/set(DOLPHIN_VERSION_MINOR "$(DOLPHIN_EMU_VERSION_MINOR)")/' $(@D)/CMake/ScmRevGen.cmake
endef

DOLPHIN_EMU_PRE_CONFIGURE_HOOKS = DOLPHIN_EMU_PRE_CONFIGURE_HOOK

$(eval $(cmake-package))
$(eval $(emulator-info-package))
