#!/usr/bin/env python
import batoceraFiles
import Command
import controllersConfig
from generators.Generator import Generator
import os
from os import path
import shlex

class GzdoomGenerator(Generator):
    def generate(self, system, rom, playersControllers, guns, gameResolution):
        config_dir = f"{batoceraFiles.CONF}/gzdoom"
        if not os.path.exists(config_dir):
            os.mkdir(config_dir)

        extra_config = 'bind ] weapnext\n'

        f=open('/usr/share/batocera/batocera.arch')
        arch=f.readline().strip('\n')
        if 'x86_64' in arch:
                extra_config += (
                    # Use the Vulkan render:
                    'vid_rendermode 4\n'
                    'vid_preferbackend 1\n'
                )
        else:
            extra_config += (
                # Use the GLES render:
                'vid_rendermode 4\n'
                'vid_preferbackend 3\n'
                # This setting greatly improves performance:
                'gles_use_mapped_buffer true\n'
                )

        iwad = ''
        pwad = ''

        if rom.endswith(".gzdoom"):
            with open(rom, "r") as f:
                iwad_command = f.read().strip()
            args = shlex.split(iwad_command)
        elif rom.endswith(".uwad"):
            f=open(rom)
            content=f.readlines()
            for line in content:
                if 'IWAD=/' in line:
                    iwad += line.replace('IWAD=', '').replace('\n', ' ')
                elif 'PWAD=/' in line:
                    pwad += line.replace('PWAD=', '').replace('\n', ' ')
            iwad_command = '-iwad ' + iwad + '-file ' + pwad
            args = shlex.split(iwad_command)
        else:
            iwad_command = '-iwad ' + rom
            args = shlex.split(iwad_command)

        # A script file with console commands that are always ran when a game starts
        script_file = f"{config_dir}/gzdoom.cfg"
        with open(script_file, "w") as script:
            script.write(
                "# This file is automatically generated by gzdoomGenerator.py\n"
                # In the code, logfile does not appear to be created unless done so explicitly
                f"logfile {batoceraFiles.logdir}/gzdoom.log\n"
                f"vid_fps {'true' if system.getOptBoolean('showFPS') else 'false'}\n"
                f"{extra_config}"
                "echo BATOCERA\n"  # easy check that script ran in console
            )

        return Command.Command(
            array=[
                '/usr/share/gzdoom/gzdoom',
                *args,
                '-exec', script_file,
                # Disable controllers because support is poor; use evmapy instead
                '-nojoy',
                '-fullscreen',
                '-width', str(gameResolution['width']),
                '-height', str(gameResolution['height']),
            ],
            env={
                'DOOMWADDIR': '/userdata/roms/ports/doom',
                'SDL_AUTO_UPDATE_JOYSTICKS': '0'
            }
        )
