################################################################################
#
# azahar
#
################################################################################
# Version: Commits on Jan 19, 2026
AZAHAR_VERSION = 64516e64208d3869cef295ed73e2a02b6310241a
AZAHAR_SITE = https://github.com/azahar-emu/azahar.git
AZAHAR_SITE_METHOD=git
AZAHAR_GIT_SUBMODULES = YES
AZAHAR_LICENSE = GPLv2
AZAHAR_SUPPORTS_IN_SOURCE_BUILD = NO

AZAHAR_DEPENDENCIES += boost cubeb fdk-aac ffmpeg fmt openal sdl2

AZAHAR_CONF_OPTS += -DAZAHAR_ENABLE_COMPATIBILITY_REPORTING=ON
AZAHAR_CONF_OPTS += -DAZAHAR_WARNINGS_AS_ERRORS=OFF
AZAHAR_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
AZAHAR_CONF_OPTS += -DCITRA_ENABLE_BUNDLE_TARGET=ON
AZAHAR_CONF_OPTS += -DCITRA_WARNINGS_AS_ERRORS=OFF
AZAHAR_CONF_OPTS += -DDYNARMIC_WARNINGS_AS_ERRORS=OFF
AZAHAR_CONF_OPTS += -DENABLE_COMPATIBILITY_LIST_DOWNLOAD=ON
AZAHAR_CONF_OPTS += -DENABLE_LTO=ON
AZAHAR_CONF_OPTS += -DENABLE_OPENAL=OFF
AZAHAR_CONF_OPTS += -DENABLE_ROOM_STANDALONE=OFF
AZAHAR_CONF_OPTS += -DENABLE_ROOM=OFF
AZAHAR_CONF_OPTS += -DENABLE_SDL2=ON
AZAHAR_CONF_OPTS += -DENABLE_SOFTWARE_RENDERER=ON
AZAHAR_CONF_OPTS += -DENABLE_TESTS=OFF
AZAHAR_CONF_OPTS += -DENABLE_WEB_SERVICE=OFF
AZAHAR_CONF_OPTS += -DUSE_DISCORD_PRESENCE=OFF
AZAHAR_CONF_OPTS += -DUSE_SYSTEM_BOOST=ON
AZAHAR_CONF_OPTS += -DUSE_SYSTEM_CUBEB=ON
AZAHAR_CONF_OPTS += -DUSE_SYSTEM_OPENAL=ON
AZAHAR_CONF_OPTS += -DUSE_SYSTEM_SDL2=ON

ifeq ($(BR2_X86_CPU_HAS_SSE42),y)
    AZAHAR_CONF_OPTS += -DENABLE_SSE42=ON
else
    AZAHAR_CONF_OPTS += -DENABLE_SSE42=OFF
endif

ifeq ($(BR2_PACKAGE_QT6),y)
    AZAHAR_DEPENDENCIES += qt6base qt6tools qt6multimedia
    AZAHAR_CONF_OPTS += -DENABLE_QT=ON
    AZAHAR_CONF_OPTS += -DENABLE_QT_TRANSLATION=ON
    AZAHAR_CONF_OPTS += -DENABLE_QT_UPDATE_CHECKER=OFF
else
    AZAHAR_CONF_OPTS += -DENABLE_QT=OFF
    AZAHAR_CONF_OPTS += -DENABLE_SDL2_FRONTEND=ON
endif

ifeq ($(BR2_PACKAGE_BATOCERA_VULKAN),y)
    AZAHAR_CONF_OPTS += -DENABLE_VULKAN=ON
    AZAHAR_DEPENDENCIES += vulkan-headers vulkan-loader
else
    AZAHAR_CONF_OPTS += -DENABLE_VULKAN=OFF
endif

AZAHAR_CONF_ENV += LDFLAGS=-lpthread

define AZAHAR_INSTALL_TARGET_CMDS
	mkdir -p $(TARGET_DIR)/usr/bin
	$(INSTALL) -D $(@D)/buildroot-build/bin/Release/azahar $(TARGET_DIR)/usr/bin/
endef

define AZAHAR_EVMAPY
	mkdir -p $(TARGET_DIR)/usr/share/evmapy
	cp -prn $(BR2_EXTERNAL_BATOCERA_PATH)/package/batocera/emulators/azahar/3ds.azahar.keys $(TARGET_DIR)/usr/share/evmapy
endef

AZAHAR_POST_INSTALL_TARGET_HOOKS = AZAHAR_EVMAPY

$(eval $(cmake-package))
