nds:
  emulator: libretro
  core:     melonds
fmtowns:
  emulator: libretro
  core:     mame
flash:
  emulator: lightspark
  core:     lightspark
atomiswave:
  emulator: libretro
  core:     flycast
dreamcast:
  emulator: libretro
  core:     flycast
naomi:
  emulator: libretro
  core:     flycast
model2:
  emulator: libretro
  core:     mame
