[tool.pyright]
exclude = [".venv*", "buildroot*", "output", "dl"]
stubPath = "python-stubs"

pythonVersion = "3.12"
pythonPlatform = "Linux"

strictListInference = true
strictDictionaryInference = true
strictSetInference = true
reportMissingModuleSource = "none"

[tool.ruff]
extend-exclude = [".venv*", "buildroot*", "output", "dl"]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
select = ["TCH", "PYI", "I", "UP", "F", "E", "W", "B", "C4", "SIM", "PTH", "G", "RUF"]
ignore = ["SIM105", "E501"]

[tool.ruff.lint.isort]
extra-standard-library = ["typing_extensions", "_typeshed"]
known-first-party = ["configgen"]
combine-as-imports = true
