#!/bin/bash
clear
echo '-------------------------------------------------------'
echo 'You are about to update the Raspberry Pi4 Firmware'
echo 'This could be Dangerous if not done correctly'
echo '-------------------------------------------------------'
read -p "Do you want to proceed? (yes/no)" yn

case $yn in 
	yes ) echo echo Proceeding with the firmware update...;;
	no ) echo NOT applying Firmware update
		exit;;
	* ) echo NOT applying Firmware update
		exit 1;;
esac
mount -o remount,rw /boot
/usr/bin/rpi-eeprom-update -a
