#!/bin/sh

# This is the BATOCERA system splash service
# It shows the unique BATOCERA logo in early boot stage
screen_rotate="$(/usr/bin/batocera-settings-get-master display.rotate)"
screen_rotate_edp="$(/usr/bin/batocera-settings-get-master display.rotate.eDP)"
screen_x=$(cat /sys/class/graphics/fb0/virtual_size | cut -d "," -f1)
screen_y=$(cat /sys/class/graphics/fb0/virtual_size | cut -d "," -f2)
image="/usr/share/batocera/splash/boot-logo.png"
LOG_FILE="/var/log/splash.log"
STOP_FILE="/var/run/system-splash.stop"

do_start ()
{
    LOG_DIR="${LOG_FILE%/*}"
    [ -d "${LOG_DIR}" ] || mkdir -p "${LOG_DIR}"
    exec >> "${LOG_FILE}" 2>&1
    
    if [ ! -e /dev/fb0 ]; then
        i=0
        while [ ! -e /dev/fb0 ] && [ $i -lt 50 ]; do
            sleep 0.1
            i=$((i + 1))
        done
        if [ ! -e /dev/fb0 ]; then
            echo "Error: Framebuffer device /dev/fb0 not found."
            exit 1
        fi
    fi

    draw_logo || exit 1

    # the gpu driver replaces the firmware framebuffer, clearing the screen
    fbname=""
    [ -r /sys/class/graphics/fb0/name ] && read -r fbname < /sys/class/graphics/fb0/name
    i=0
    while [ $i -lt 120 ] && [ ! -e "${STOP_FILE}" ]; do
        sleep 0.5
        i=$((i + 1))
        newname=""
        [ -r /sys/class/graphics/fb0/name ] && read -r newname < /sys/class/graphics/fb0/name
        if [ -n "${newname}" ] && [ "${newname}" != "${fbname}" ]; then
            fbname="${newname}"
            echo "Framebuffer changed to ${fbname}, redrawing."
            draw_logo || exit 1
        fi
    done
}

draw_logo () {
    # V_BOARD_MODEL detection from batocera-model
    V_BOARD_MODEL=$(batocera-model)

    if [ "$screen_rotate" = "1" ]; then
        convert "/usr/share/batocera/splash/boot-logo.png" -rotate -270 -quality 75 "/tmp/boot-logo.png"
        image="/tmp/boot-logo.png"
    elif [ "$screen_rotate" = "2" ]; then
        convert "/usr/share/batocera/splash/boot-logo.png" -rotate -180 -quality 75 "/tmp/boot-logo.png"
        image="/tmp/boot-logo.png"
    elif [ "$screen_rotate" = "3" ]; then
        convert "/usr/share/batocera/splash/boot-logo.png" -rotate -90 -quality 75 "/tmp/boot-logo.png"
        image="/tmp/boot-logo.png"
    fi

    if [ "$screen_rotate_edp" = "1" ]; then
        convert "/usr/share/batocera/splash/boot-logo.png" -rotate -270 -quality 75 "/tmp/boot-logo.png"
        image="/tmp/boot-logo.png"
    elif [ "$screen_rotate_edp" = "2" ]; then
        convert "/usr/share/batocera/splash/boot-logo.png" -rotate -180 -quality 75 "/tmp/boot-logo.png"
        image="/tmp/boot-logo.png"
    elif [ "$screen_rotate_edp" = "3" ]; then
        convert "/usr/share/batocera/splash/boot-logo.png" -rotate -90 -quality 75 "/tmp/boot-logo.png"
        image="/tmp/boot-logo.png"
    fi

    convert "${image}" -resize "$screen_x"x"$screen_y"! -quality 75 "/tmp/boot-logo.png"

    FBV_OPTS="-f -e -i"
    # FBV_OPTS can be set differently for some boards to work
    test -e /dev/fb0 && fbv ${FBV_OPTS} "/tmp/boot-logo.png"
}

do_stop () {
    touch "${STOP_FILE}"
    [ -e /dev/fb0 ] && dd if=/dev/zero of=/dev/fb0 >/dev/null 2>&1
}

case "$1" in
    start)
        do_start &
        ;;
    stop)
        do_stop
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit $?