#!/bin/sh

# This is the BATOCERA system splash service
# It shows the unique BATOCERA logo in early boot stage
screen_rotate="$(/usr/bin/batocera-settings-get-master display.rotate)"
screen_rotate_edp="$(/usr/bin/batocera-settings-get-master display.rotate.eDP)"
screen_x=$(cat /sys/class/graphics/fb0/virtual_size | cut -d "," -f1)
screen_y=$(cat /sys/class/graphics/fb0/virtual_size | cut -d "," -f2)
image="/usr/share/batocera/splash/boot-logo.png"

do_start ()
{
    # on some sytems, fb0 is not immediatly loaded, so, keep a chance by waiting a bit
    # are we sure all boards have fb0 ?!
    N=0
    while ! test -e /dev/fb0 -o $N -gt 80
    do
        sleep 0.1
        N=$((N+1))
    done

    # V_BOARD_MODEL detection from batocera-model
    V_BOARD_MODEL=$(batocera-model)

    if [ "$screen_rotate" = "1" ]; then
        convert "/usr/share/batocera/splash/boot-logo.png" -rotate -270 -quality 75 "/tmp/boot-logo.png"
        image="/tmp/boot-logo.png"
    elif [ "$screen_rotate" = "2" ]; then
        convert "/usr/share/batocera/splash/boot-logo.png" -rotate -180 -quality 75 "/tmp/boot-logo.png"
        image="/tmp/boot-logo.png"
    elif [ "$screen_rotate" = "3" ]; then
        convert "/usr/share/batocera/splash/boot-logo.png" -rotate -90 -quality 75 "/tmp/boot-logo.png"
        image="/tmp/boot-logo.png"
    fi

    if [ "$screen_rotate_edp" = "1" ]; then
        convert "/usr/share/batocera/splash/boot-logo.png" -rotate -270 -quality 75 "/tmp/boot-logo.png"
        image="/tmp/boot-logo.png"
    elif [ "$screen_rotate_edp" = "2" ]; then
        convert "/usr/share/batocera/splash/boot-logo.png" -rotate -180 -quality 75 "/tmp/boot-logo.png"
        image="/tmp/boot-logo.png"
    elif [ "$screen_rotate_edp" = "3" ]; then
        convert "/usr/share/batocera/splash/boot-logo.png" -rotate -90 -quality 75 "/tmp/boot-logo.png"
        image="/tmp/boot-logo.png"
    fi

    convert "${image}" -resize "$screen_x"x"$screen_y"! -quality 75 "/tmp/boot-logo.png"

    FBV_OPTS="-f -e -i"
    # FBV_OPTS can be set differently for some boards to work
    test -e /dev/fb0 && fbv ${FBV_OPTS} "/tmp/boot-logo.png"
}

do_stop () {
    if [ -e /dev/fb0 ]; then
        dd if=/dev/zero of=/dev/fb0 >/dev/null 2>&1
    fi
}

case "$1" in
    start)
        do_start &
        ;;
    stop)
        do_stop
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit $?
