#!/bin/bash

if [ -n "$WAYLAND_DISPLAY" ]; then
    export SDL_VIDEODRIVER=wayland
    export SDL_VIDEO_WAYLAND_WMCLASS="batocera-config-vita3k"
else
    export DISPLAY=$(getLocalXDisplay)
fi

# set the environment variables
export XDG_CONFIG_HOME="/userdata/system/configs"
export XDG_CACHE_HOME="/userdata/system/cache"
export XDG_DATA_HOME="/userdata/saves"

# Now run the emulator
if [[ -x /usr/bin/vita3k/Vita3K ]]; then
    echo "Starting Vita3K..."
    USER=root \
    QT_PLUGIN_PATH=/usr/lib/qt6/plugins \
    QT_QPA_PLATFORM=xcb \
    QT_XCB_NO_XI2=1 \
    /usr/bin/vita3k/Vita3K
else
    echo "System not found."
    exit 1
fi
