#!/bin/bash

# when the program is called from a non X environment, handle the mouse
# maybe an other choice is better

if test -z "${DISPLAY}"
then
    export DISPLAY=$(getLocalXDisplay)
fi

XDG_CONFIG_HOME="/userdata/system/configs" XDG_DATA_HOME="/userdata/saves/triforce" XDG_CACHE_HOME="/userdata/system/cache" QT_QPA_PLATFORM="xcb" QT_XCB_NO_XI2="1" /usr/bin/dolphin-triforce -u "/userdata/system/configs/dolphin-triforce"
