#!/bin/bash

if test -z "${DISPLAY}"
then
    export DISPLAY=$(getLocalXDisplay)
fi

# Define the directory paths
configPath="/userdata/system/configs/shadPS4"
dlcPath="/userdata/roms/ps4/DLC"

# Check if the directory exists, and create it if it doesn't
if [ ! -d "$configPath" ]; then
    mkdir -p "$configPath"
    if [ $? -eq 0 ]; then
        echo "Directory created successfully."
    else
        echo "Failed to create directory."
        exit 1
    fi
fi

if [ ! -d "$dlcPath" ]; then
    mkdir -p "$dlcPath"
    if [ $? -eq 0 ]; then
        echo "Directory created successfully."
    else
        echo "Failed to create directory."
        exit 1
    fi
fi

if [[ -x /usr/bin/shadPS4QtLauncher ]]; then
    echo "Starting shadPS4QtLauncher..."
    USER=root \
    QT_PLUGIN_PATH=/usr/lib/qt6/plugins \
    QT_QPA_PLATFORM=xcb \
    QT_XCB_NO_XI2=1 \
    /usr/bin/shadPS4QtLauncher
else
    echo "System not found."
    exit 1
fi
