#!/bin/bash

# when the program is called from a non X environment, handle the mouse
# maybe an other choice is better

if test -z "${DISPLAY}"
then
    export DISPLAY=$(getLocalXDisplay)
fi

if [[ -x /usr/bin/transmission-qt ]]; then
    QT_PLUGIN_PATH="/usr/lib/qt6/plugins" \
    QT_QPA_PLATFORM=xcb \
    QT_XCB_NO_XI2=1 \
    /usr/bin/transmission-qt
else
    echo "System not found."
    exit 1
fi
