#!/bin/bash

# when the program is called from a non X environment, handle the mouse
# maybe an other choice is better

if test -z "${DISPLAY}"
then
    export DISPLAY=$(getLocalXDisplay)
fi

export XDG_CONFIG_HOME=/userdata/system/configs

/usr/bin/pcsx2/pcsx2
