## RETRO
default:
  # shader affects retroarch shaders
  shader: eagle/super-eagle
  # scanline affect fba2x
  scanline: false
snes:
  shader: eagle/super-eagle
nes:
  shader: eagle/super-eagle
n64:
  shader: eagle/super-eagle
gba:
  shader: handheld/lcd3x
gb:
  shader: handheld/lcd3x
gbc:
  shader: handheld/lcd3x
fds:
  shader: eagle/super-eagle
virtualboy:
  shader: eagle/super-eagle
# Sega
sg1000:
  shader: eagle/super-eagle
mastersystem:
  shader: eagle/super-eagle
megadrive:
  shader: eagle/super-eagle
gamegear:
  shader: eagle/super-eagle
sega32x:
  shader: eagle/super-eagle
segacd:
  shader: eagle/super-eagle
# Arcade
neogeo:
  shader: eagle/super-eagle
neogeocd:
  shader: eagle/super-eagle
mame:
  shader: eagle/super-eagle
fba:
  shader: eagle/super-eagle
naomi:
  shader: eagle/super-eagle
atomiswave:
  shader: eagle/super-eagle
# Consoles
ngp:
  shader: handheld/lcd3x
ngpc:
  shader: handheld/lcd3x
gw:
  shader: eagle/super-eagle
vectrex:
  shader: handheld/lcd3x
lynx:
  shader: handheld/lcd3x
lutro:
  shader: eagle/super-eagle
wswan:
  shader: handheld/lcd3x
wswanc:
  shader: handheld/lcd3x
pcengine:
  shader: eagle/super-eagle
pcenginecd:
  shader: eagle/super-eagle
supergrafx:
  shader: eagle/super-eagle
atari800:
  shader: eagle/super-eagle
atari2600:
  shader: eagle/super-eagle
atari5200:
  shader: eagle/super-eagle
atari7800:
  shader: eagle/super-eagle
prboom:
  shader: eagle/super-eagle
psx:
  shader: eagle/super-eagle
colecovision:
  shader: eagle/super-eagle
# Computers
msx:
  shader: eagle/super-eagle
msx1:
  shader: eagle/super-eagle
msx2:
  shader: eagle/super-eagle
amiga:
  shader: eagle/super-eagle
amstradcpc:
  shader: eagle/super-eagle
atarist:
  shader: eagle/super-eagle
zxspectrum:
  shader: eagle/super-eagle
odyssey2:
  shader: eagle/super-eagle
zx81:
  shader: eagle/super-eagle
pcfx:
  shader: eagle/super-eagle
x68000:
  shader: eagle/super-eagle
