name: Request a feature
description: Request a feature to improve Batocera.
body:
  - type: markdown
    attributes:
      value: "## WARNING - READ CAREFULLY"
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in requesting a new feature or enhancement for Batocera!
        Feature requests will NOT be accepted via Github Issues.  Requests filed here will be closed.
        To file a request, please join us on Discord and use the appropriate request channel:
        - Batocera.linux requests, for emulation and general operating system features: https://discord.gg/hgNcPXrQDH
        - EmulationStation GUI requests, for features in the ES front-end: https://discord.gg/vpnbV2KeBH
