name: Request for support
description: Request support with using the Batocera.linux system
body:
  - type: markdown
    attributes:
      value: "## WARNING - READ CAREFULLY"
  - type: markdown
    attributes:
      value: |
        Support requests will NOT be accepted via Github Issues.  Requests filed here will be closed.
        For support with using Batoceram please join us on Discord in our Help and Support channel: https://discord.gg/p7K5v5TZ3k
