#!/bin/bash

# hide mouse cursor
unclutter --timeout 1 -b

# disable dpms to prevent screen from blanking
xset -dpms
xset s off

# allow coredumps for ES
ulimit -c unlimited

xrdb -merge /etc/openbox/Xresources
openbox --config-file /etc/openbox/rc.xml --startup "emulationstation-standalone"
