################################################################################
#
# thextech
#
################################################################################
# Version: Commits on Oct 07, 2025
THEXTECH_VERSION = 7fee595ee997566aa7ede6bdec9d9adb6914f74d
THEXTECH_SITE = https://github.com/TheXTech/TheXTech
THEXTECH_SITE_METHOD = git
THEXTECH_GIT_SUBMODULES = YES
THEXTECH_LICENSE = GPLv3
THEXTECH_DEPENDENCIES = sdl2 sdl2_mixer sdl2_ttf

THEXTECH_CONF_ENV = GIT_DISCOVERY_ACROSS_FILESYSTEM=1
THEXTECH_CONF_OPTS += -DUSE_SYSTEM_LIBS_DEFAULT=ON
THEXTECH_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
THEXTECH_CONF_OPTS += -DUSE_SYSTEM_SDL2=ON
THEXTECH_CONF_OPTS += -DUSE_SYSTEM_ZLIB=ON
THEXTECH_CONF_OPTS += -DTHEXTECH_ENABLE_TTF_SUPPORT=ON
THEXTECH_CONF_OPTS += -DTHEXTECH_FORCE_FULLSCREEN=ON
THEXTECH_CONF_OPTS += -DCMAKE_C_COMPILER=$(HOST_DIR)/bin/$(GNU_TARGET_NAME)-gcc
THEXTECH_CONF_OPTS += -DCMAKE_CXX_COMPILER=$(HOST_DIR)/bin/$(GNU_TARGET_NAME)-g++

ifneq ($(BR2_PACKAGE_HAS_LIBGL),y)
    THEXTECH_CONF_OPTS += -DTHEXTECH_BUILD_GL_DESKTOP_MODERN=OFF
    THEXTECH_CONF_OPTS += -DTHEXTECH_BUILD_GL_DESKTOP_LEGACY=OFF
ifeq ($(BR2_PACKAGE_BATOCERA_GLES3),y)
    THEXTECH_CONF_OPTS += -DTHEXTECH_BUILD_GL_ES_MODERN=ON
    THEXTECH_CONF_OPTS += -DTHEXTECH_BUILD_GL_ES_LEGACY=OFF
else ifeq ($(BR2_PACKAGE_BATOCERA_GLES2),y)
    THEXTECH_CONF_OPTS += -DTHEXTECH_BUILD_GL_ES_MODERN=OFF
    THEXTECH_CONF_OPTS += -DTHEXTECH_BUILD_GL_ES_LEGACY=ON
endif
endif

ifeq ($(BR2_PACKAGE_HAS_LIBMALI),y)
    THEXTECH_CONF_OPTS += -DCMAKE_EXE_LINKER_FLAGS=-lmali
    THEXTECH_CONF_OPTS += -DCMAKE_SHARED_LINKER_FLAGS=-lmali
endif

define THEXTECH_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/output/bin/thextech $(TARGET_DIR)/usr/bin/
	cp -avf $(@D)/output/lib/libSDL2_mixer_ext.so* $(TARGET_DIR)/usr/lib/
endef

define THEXTECH_NO_ASM
	$(SED) "s|OPUS_ARM_ASM AND CMAKE_COMPILER_IS_GNUCC|OPUS_ARM_NO_ASM AND CMAKE_COMPILER_IS_GNUCC|g" $(@D)/3rdparty/AudioCodecs/libopus/CMakeLists.txt
endef

THEXTECH_POST_EXTRACT_HOOKS = THEXTECH_NO_ASM

$(eval $(cmake-package))
