################################################################################
#
# citra
#
################################################################################
# Version: Commits on Mar 10, 2025
CITRA_VERSION = e0d78ada69000bf2ad808873c3852f3ef64c80da
CITRA_SITE = https://github.com/Borked3DS/Borked3DS.git
CITRA_SITE_METHOD=git
CITRA_GIT_SUBMODULES=YES
CITRA_LICENSE = GPLv2
CITRA_DEPENDENCIES += boost catch2 cubeb fdk-aac ffmpeg fmt libbacktrace qt6base qt6multimedia qt6tools sdl2
CITRA_SUPPORTS_IN_SOURCE_BUILD = NO

CITRA_CONF_OPTS += -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld -lstdc++"
CITRA_CONF_OPTS += -DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=lld -lstdc++"
CITRA_CONF_OPTS += -DBORKED3DS_USE_PRECOMPILED_HEADERS=OFF
CITRA_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
CITRA_CONF_OPTS += -DCITRA_WARNINGS_AS_ERRORS=OFF
CITRA_CONF_OPTS += -DDISABLE_SYSTEM_BOOST=ON
CITRA_CONF_OPTS += -DDISABLE_SYSTEM_CPP_HTTPLIB=ON
CITRA_CONF_OPTS += -DDISABLE_SYSTEM_CPP_JWT=ON
CITRA_CONF_OPTS += -DDISABLE_SYSTEM_CRYPTOPP=ON
CITRA_CONF_OPTS += -DDISABLE_SYSTEM_DYNARMIC=ON
CITRA_CONF_OPTS += -DDISABLE_SYSTEM_FFMPEG_HEADERS=ON
CITRA_CONF_OPTS += -DDISABLE_SYSTEM_INIH=ON
CITRA_CONF_OPTS += -DDISABLE_SYSTEM_LODEPNG=ON
CITRA_CONF_OPTS += -DDISABLE_SYSTEM_VMA=ON
CITRA_CONF_OPTS += -DDISABLE_SYSTEM_XBYAK=ON
CITRA_CONF_OPTS += -DDISABLE_SYSTEM_ZSTD=ON
CITRA_CONF_OPTS += -DENABLE_LTO=OFF
CITRA_CONF_OPTS += -DENABLE_SDL2=ON
CITRA_CONF_OPTS += -DENABLE_WEB_SERVICE=ON
CITRA_CONF_OPTS += -DUSE_DISCORD_PRESENCE=OFF
CITRA_CONF_OPTS += -DUSE_SYSTEM_LIBS=ON

CITRA_CONF_ENV += LDFLAGS=-lpthread

define CITRA_INSTALL_TARGET_CMDS
	mkdir -p $(TARGET_DIR)/usr/bin
	$(INSTALL) -D $(@D)/buildroot-build/bin/Release/borked3ds $(TARGET_DIR)/usr/bin/citra-qt
endef

define CITRA_EVMAP
	mkdir -p $(TARGET_DIR)/usr/share/evmapy
	cp -f $(BR2_EXTERNAL_BATOCERA_PATH)/package/batocera/emulators/citra/3ds.citra.keys $(TARGET_DIR)/usr/share/evmapy
endef

define CITRA_NO_DL_EXTERNAL
	sed -i '/(DownloadExternals)/d' $(@D)/CMakeLists.txt
endef

CITRA_POST_INSTALL_TARGET_HOOKS = CITRA_EVMAP
CITRA_PRE_CONFIGURE_HOOKS += CITRA_NO_DL_EXTERNAL

$(eval $(cmake-package))
