default:
  options:
    video_threaded: true
    videomode: max-1280x720
    hud_support: true
amiga500:
  emulator: amiberry
  core:     A500
amiga1200:
  emulator: amiberry
  core:     A1200
amigacd32:
  emulator: amiberry
  core:     CD32
snes:
  emulator: libretro
  core:     snes9x_next
nds:
  emulator: drastic
  core:     drastic
