default:
  options:
    ratio: "full"
    retroarch.menu_driver: rgui
    retroarch.audio_out_rate: 44100
    video_threaded: true
    audio_latency: 96
    retroarch.vrr_runloop_enable: false
    retroarch.video_max_swapchain_images: 3
    retroarch.video_adaptive_vsync: true

nds:
  emulator: drastic
  core:     drastic
