default:
  options:
    video_threaded: true

n64:
  emulator: libretro
  core: parallel_n64
psp:
  options:
    frameskip: true
amiga:
  emulator: libretro
  core:     puae
amigacd32:
  emulator: libretro
  core:     puae
amigacdtv:
  emulator: libretro
  core:     puae
