n64:
  emulator: mupen64plus
  core: glide64mk2
mastersystem:
  emulator: libretro
  core:     genesisplusgx
megadrive:
  emulator: libretro
  core:     genesisplusgx
segacd:
  emulator: libretro
  core:     genesisplusgx