default:
  options:
    video_threaded: true

n64:
  emulator: mupen64plus
  core: glide64mk2
psp:
  options:
    frameskip: true
amiga500:
  emulator: amiberry
  core:     A500
amiga1200:
  emulator: amiberry
  core:     A1200
amigacd32:
  emulator: amiberry
  core:     CD32
psx:
  options:
    # menu retroarch
    # settings to fix sound issue only on Odroid XU4
    retroarch.audio_latency:      128
    retroarch.audio_out_rate:     44100
    retroarch.audio_rate_control: true
    retroarch.audio_sync:         true
    retroarch.video_hard_sync:    true
