default:
  options:
    video_threaded: true
    rewind:         false
    videomode:      CEA 4 HDMI

snes:
  emulator: libretro
  core:     pocketsnes
gba:
  emulator: libretro
  core:     gpsp
mame:
  emulator: libretro
  core:     imame4all
nes:
  emulator: libretro
  core:     fceumm
neogeo:
  emulator: fba2x
amiga500:
  emulator: amiberry
  core:     A500
amiga500p:
  emulator: amiberry
  core:     A500P
amiga1200:
  emulator: amiberry
  core:     A1200
amiga4000:
  emulator: amiberry
  core:     A4000
amigacd32:
  emulator: amiberry
  core:     CD32
