default:
  options:
    ratio: "full"
    retroarch.menu_driver: rgui
    retroarch.audio_out_rate: 44100
    retroarch.video_max_swapchain_images: 1
    retroarch.vrr_runloop_enable: false

nds:
  emulator: drastic
  core:     drastic
psp:
  options:
    frameskip: automatic
gamecube:
  emulator: libretro
  core:     dolphin
sgb:
  emulator: libretro
  core:     mgba
wii:
  emulator: libretro
  core:     dolphin

# mess
lcdgames:
  emulator: mame
  core:     mame
cdi:
  emulator: mame
  core:     mame
advision:
  emulator: mame
  core:     mame
tvgames:
  emulator: mame
  core:     mame
pv1000:
  emulator: mame
  core:     mame
gamate:
  emulator: mame
  core:     mame
crvision:
  emulator: mame
  core:     mame
gamecom:
  emulator: mame
  core:     mame
fm7:
  emulator: mame
  core:     mame
gamepock:
  emulator: mame
  core:     mame
apfm1000:
  emulator: mame
  core:     mame
bbc:
  emulator: mame
  core:     mame
adam:
  emulator: mame
  core:     mame
arcadia:
  emulator: mame
  core:     mame
gmaster:
  emulator: mame
  core:     mame
astrocde:
  emulator: mame
  core:     mame
ti99:
  emulator: mame
  core:     mame
tutor:
  emulator: mame
  core:     mame
coco:
  emulator: mame
  core:     mame
