default:
  options:
    retroarch.audio_driver: tinyalsa

nds:
  emulator: drastic
  core:     drastic
psp:
  options:
    frameskip: automatic
psx:
  emulator: libretro
  core:     duckstation
  options:
    gpu_software: true
