default:
  options:
    retroarch.menu_driver: ozone
    retroarch.vrr_runloop_enable: false
    retroarch.video_max_swapchain_images: 3
    retroarch.video_adaptive_vsync: true
    hud_support: true
    retroarch.menu_scale_factor: 0.800000
    retroarch.menu_widget_scale_auto: false
    retroarch.menu_widget_scale_factor: 0.800000

nds:
  emulator: drastic
  core:     drastic
flash:
  emulator: lightspark
  core:     lightspark
psp:
  options:
    frameskip: automatic
gamecube:
  emulator: libretro
  core:     dolphin
sgb:
  emulator: libretro
  core:     mgba
wii:
  emulator: libretro
  core:     dolphin
