default:
  options:
    retroarch.menu_driver: ozone
    retroarch.vrr_runloop_enable: false
    retroarch.video_max_swapchain_images: 3
    retroarch.video_adaptive_vsync: true
    hud_support: true

nds:
  emulator: drastic
  core:     drastic
flash:
  emulator: lightspark
  core:     lightspark
psp:
  options:
    frameskip: automatic
gamecube:
  emulator: libretro
  core:     dolphin
sgb:
  emulator: libretro
  core:     mgba
wii:
  emulator: libretro
  core:     dolphin

# mess
lcdgames:
  emulator: mame
  core:     mame
cdi:
  emulator: mame
  core:     mame
advision:
  emulator: mame
  core:     mame
plugnplay:
  emulator: mame
  core:     mame
megaduck:
  emulator: mame
  core:     mame
pv1000:
  emulator: mame
  core:     mame
gamate:
  emulator: mame
  core:     mame
crvision:
  emulator: mame
  core:     mame
gamecom:
  emulator: mame
  core:     mame
fm7:
  emulator: mame
  core:     mame
gamepock:
  emulator: mame
  core:     mame
apfm1000:
  emulator: mame
  core:     mame
bbc:
  emulator: mame
  core:     mame
adam:
  emulator: mame
  core:     mame
arcadia:
  emulator: mame
  core:     mame
gmaster:
  emulator: mame
  core:     mame
astrocde:
  emulator: mame
  core:     mame
ti99:
  emulator: mame
  core:     mame
tutor:
  emulator: mame
  core:     mame
coco:
  emulator: mame
  core:     mame
macintosh:
  emulator: mame
  core:     mame
archimedes:
  emulator: mame
  core:     mame
socrates:
  emulator: mame
  core:     mame
supracan:
  emulator: mame
  core:     mame
vsmile:
  emulator: mame
  core:     mame
xegs:
  emulator: mame
  core:     mame
atom:
  emulator: mame
  core:     mame
electron:
  emulator: mame
  core:     mame
camplynx:
  emulator: mame
  core:     mame
vgmplay:
  emulator: mame
  core:     mame
