default:
  emulator:
  core:
  options:
    hud_support:  true
    bezel:        none
    video_frame_delay_auto: true

adam:
  emulator: mame
  core:     mame
advision:
  emulator: mame
  core:     mame
apfm1000:
  emulator: mame
  core:     mame
arcadia:
  emulator: libretro
  core:     mame
  options:
    sharemameart: 0
archimedes:
  emulator: mame
  core:     mame
astrocde:
  emulator: mame
  core:     mame
atom:
  emulator: mame
  core:     mame
bbc:
  emulator: mame
  core:     mame
camplynx:
  emulator: mame
  core:     mame
cdi:
  emulator: mame
  core:     mame
coco:
  emulator: mame
  core:     mame
crvision:
  emulator: mame
  core:     mame
electron:
  emulator: mame
  core:     mame
fm7:
  emulator: mame
  core:     mame
gaelco:
  options:
    videomode: max-640x480
gamate:
  emulator: mame
  core:     mame
gamecom:
  emulator: mame
  core:     mame
gamecube:
  options:
    ubershaders: asynchronous_ubershader
    # causes issues on nvidia+dolphin
    bezel: none
gamepock:
  emulator: mame
  core:     mame
gmaster:
  emulator: mame
  core:     mame
gp32:
  emulator: mame
  core:     mame
hikaru:
  options:
    videomode: max-640x480
jaguar:
  emulator: bigpemu
  core:    bigpemu
  options:
    hud_support: false
laser310:
  emulator: mame
  core:     mame
lcdgames:
  emulator: mame
  core:     mame
macintosh:
  emulator: mame
  core:     mame
megaduck:
  emulator: mame
  core:     mame
n64:
  options:
    videomode: max-1920x1080
n64dd:
  options:
    videomode: max-1920x1080
pcengine:
  emulator: libretro
  core:     pce
pcenginecd:
  emulator: libretro
  core:     pce
pdp1:
  emulator: mame
  core:     mame
plugnplay:
  emulator: mame
  core:     mame
psvita:
  options:
    hud_support: false
pv1000:
  emulator: mame
  core:     mame
saturn:
  emulator: libretro
  core:     beetle-saturn
sgb:
  emulator: libretro
  core:     mesens
socrates:
  emulator: mame
  core:     mame
supracan:
  emulator: mame
  core:     mame
ti99:
  emulator: mame
  core:     mame
#triforce:
#  emulator: dolphin-triforce
#  core:     dolphin-triforce
tutor:
  emulator: mame
  core:     mame
vc4000:
  emulator: mame
  core:     mame
vgmplay:
  emulator: mame
  core:     mame
vsmile:
  emulator: mame
  core:     mame
wii:
  options:
    ubershaders: asynchronous_ubershader
    # causes issues on nvidia+dolphin
    bezel: none
xegs:
  emulator: mame
  core:     mame
