default:
  options:
    ratio: "full"
    retroarch.menu_driver: rgui
    retroarch.audio_out_rate: 44100
    retroarch.vrr_runloop_enable: "true"
    retroarch.menu_widget_scale_auto: "true"
    retroarch.audio_latency: 96
    video_threaded: true
    hud_support: false

amiga500:
  emulator: libretro
  core:     uae4arm
amiga1200:
  emulator: libretro
  core:     uae4arm
amigacd32:
  emulator: libretro
  core:     uae4arm
amigacdtv:
  emulator: libretro
  core:     uae4arm
nds:
  emulator: drastic
  core:     drastic
fmtowns:
  emulator: libretro
  core:     mame
psx:
  options:
    gpu_software: true
