default:
  options:
    retroarch.menu_driver: ozone
    retroarch.vrr_runloop_enable: false
    retroarch.video_max_swapchain_images: 3
    retroarch.video_adaptive_vsync: true
    hud_support: true
    retroarch.menu_scale_factor: 0.800000
    retroarch.menu_widget_scale_auto: false
    retroarch.menu_widget_scale_factor: 0.800000

atomiswave:
  emulator: flycast
  core:     flycast
  gfxbackend: vulkan
c20:
  emulator: libretro
  core:     vice_xvic
c64:
  emulator: libretro
  core:     vice_x64
c128:
  emulator: libretro
  core:     vice_x128
cplus4:
  emulator: libretro
  core:     vice_xplus4
dreamcast:
  emulator: flycast
  core:     flycast
  gfxbackend: vulkan
flash:
  emulator: lightspark
  core:     lightspark
fmtowns:
  emulator: libretro
  core:     mess
gamecube:
  emulator: libretro
  core:     dolphin
naomi:
  emulator: flycast
  core:     flycast
  gfxbackend: vulkan
naomi2:
  emulator: flycast
  core:     flycast
  gfxbackend: vulkan
nds:
  emulator: drastic
  core:     drastic
pet:
  emulator: libretro
  core:     vice_xpet
psp:
  options:
    frameskip: automatic
sgb:
  emulator: libretro
  core:     mgba