default:
  options:
    retroarch.audio_out_rate: 44100

dos:
  emulator: dosbox
  core:     dosbox
mastersystem:
  emulator: libretro
  core:     picodrive
megadrive:
  emulator: libretro
  core:     picodrive
psp:
  options:
    frameskip: 1
snes:
  emulator: libretro
  core:     snes9x_next
n64:
  options:
    videomode: max-640x480
