pcengine:
  emulator: libretro
  core:     pce
pcenginecd:
  emulator: libretro
  core:     pce
saturn:
  emulator: libretro
  core:     beetle-saturn
n64:
  options:
    videomode: max-1920x1080
n64dd:
  options:
    videomode: max-1920x1080
sgb:
  emulator: libretro
  core:     mesen-s
lcdgames:
  emulator: mame
  core:     mame
cdi:
  emulator: mame
  core:     mame
advision:
  emulator: mame
  core:     mame