default:
  options:
    retroarch.menu_driver: ozone
    retroarch.vrr_runloop_enable: false
    retroarch.video_max_swapchain_images: 3
    retroarch.video_adaptive_vsync: true
    hud_support: true
    retroarch.menu_scale_factor: 0.800000
    retroarch.menu_widget_scale_auto: false
    retroarch.menu_widget_scale_factor: 0.800000

atomiswave:
  emulator: flycast
  core:     flycast
dreamcast:
  emulator: flycast
  core:     flycast
flash:
  emulator: lightspark
  core:     lightspark
fmtowns:
  emulator: libretro
  core:     mess
gamecube:
  emulator: libretro
  core:     dolphin
naomi:
  emulator: flycast
  core:     flycast
naomi2:
  emulator: flycast
  core:     flycast
nds:
  emulator: drastic
  core:     drastic
psp:
  options:
    frameskip: automatic
sgb:
  emulator: libretro
  core:     mgba
wii:
  emulator: libretro
  core:     dolphin
