flash:
  emulator: lightspark
  core:     lightspark
fmtowns:
  emulator: libretro
  core:     mame
nds:
  emulator: libretro
  core:     melonds
n64:
  emulator: libretro
  core:     mupen64plus-next
