################################################################################
#
# vulkan-loader
#
################################################################################
# Version: Commits on Jul 03, 2023
VULKAN_LOADER_VERSION = fdae336d4f701cfca867d97fc348ef44741acb26
VULKAN_LOADER_SITE =  $(call github,KhronosGroup,Vulkan-Loader,$(VULKAN_LOADER_VERSION))
VULKAN_LOADER_DEPENDENCIES = vulkan-headers host-ninja
VULKAN_LOADER_INSTALL_STAGING = YES

VULKAN_LOADER_CONF_OPTS += -DCMAKE_BUILD_TYPE=Release -GNinja
VULKAN_LOADER_CONF_OPTS += -DVULKAN_HEADERS_INSTALL_DIR=$(STAGING_DIR)/usr

ifeq ($(BR2_PACKAGE_XORG7),y)
VULKAN_LOADER_DEPENDENCIES += xlib_libXrandr
VULKAN_LOADER_CONF_OPTS += -DBUILD_WSI_XCB_SUPPORT=ON -DBUILD_WSI_XLIB_SUPPORT=ON -DUSE_GAS=OFF
else
VULKAN_LOADER_CONF_OPTS += -DBUILD_WSI_XCB_SUPPORT=OFF -DBUILD_WSI_XLIB_SUPPORT=OFF -DUSE_GAS=OFF
endif

ifeq ($(BR2_PACKAGE_MESA3D),y)
VULKAN_LOADER_DEPENDENCIES += mesa3d
endif

define VULKAN_LOADER_BUILD_CMDS
	$(TARGET_MAKE_ENV) $(BR2_CMAKE) --build $(VULKAN_LOADER_BUILDDIR)
endef

define VULKAN_LOADER_INSTALL_STAGING_CMDS
	$(TARGET_MAKE_ENV) DESTDIR=$(STAGING_DIR) $(BR2_CMAKE) --install $(VULKAN_LOADER_BUILDDIR)
endef

define VULKAN_LOADER_INSTALL_TARGET_CMDS
	$(TARGET_MAKE_ENV) DESTDIR=$(TARGET_DIR) $(BR2_CMAKE) --install $(VULKAN_LOADER_BUILDDIR)
endef

$(eval $(cmake-package))
