################################################################################
#
# LIBRETRO DOLPHIN
#
################################################################################
# Version.: Commits on Sep 11, 2021
LIBRETRO_DOLPHIN_VERSION = 5f3bea9d7246ec4b4e2b14ee127a7a4147e802c9
LIBRETRO_DOLPHIN_SITE = $(call github,libretro,dolphin,$(LIBRETRO_DOLPHIN_VERSION))
LIBRETRO_DOLPHIN_LICENSE = GPLv2

LIBRETRO_DOLPHIN_SUPPORTS_IN_SOURCE_BUILD = NO

LIBRETRO_DOLPHIN_CONF_OPTS  = -DLIBRETRO=ON
LIBRETRO_DOLPHIN_CONF_OPTS += -DLIBRETRO_STATIC=ON
LIBRETRO_DOLPHIN_CONF_OPTS += -DCMAKE_BUILD_TYPE=Release
LIBRETRO_DOLPHIN_CONF_OPTS += -DENABLE_NOGUI=OFF
LIBRETRO_DOLPHIN_CONF_OPTS += -DENABLE_QT=OFF
LIBRETRO_DOLPHIN_CONF_OPTS += -DENABLE_TESTS=OFF
LIBRETRO_DOLPHIN_CONF_OPTS += -DUSE_DISCORD_PRESENCE=OFF
LIBRETRO_DOLPHIN_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
LIBRETRO_DOLPHIN_CONF_OPTS += -DDISTRIBUTOR='batocera.linux'
LIBRETRO_DOLPHIN_CONF_OPTS += -DENABLE_X11=OFF

# enable vulkan if we are building with it
ifeq ($(BR2_PACKAGE_VULKAN_HEADERS)$(BR2_PACKAGE_VULKAN_LOADER),y)
	LIBRETRO_DOLPHIN_CONF_OPTS += -DVULKAN=ON
else
	LIBRETRO_DOLPHIN_CONF_OPTS += -DVULKAN=OFF
endif

ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_RPI4),y)
    LIBRETRO_DOLPHIN_CONF_OPTS += -DENABLE_EGL=OFF
endif

define LIBRETRO_DOLPHIN_INSTALL_TARGET_CMDS
        $(INSTALL) -D $(@D)/buildroot-build/dolphin_libretro.so \
                $(TARGET_DIR)/usr/lib/libretro/dolphin_libretro.so
endef

$(eval $(cmake-package))