################################################################################
#
# libretro-azahar
#
################################################################################
# Version: Commits on May 17, 2026
LIBRETRO_AZAHAR_VERSION = ab6896a2caaaaac0b2b657f490713d2d48f08ffb
LIBRETRO_AZAHAR_SITE = https://github.com/azahar-emu/azahar.git
LIBRETRO_AZAHAR_SOURCE = azahar-$(LIBRETRO_AZAHAR_VERSION)-git4.tar.gz
LIBRETRO_AZAHAR_SITE_METHOD=git
LIBRETRO_AZAHAR_GIT_SUBMODULES=YES
LIBRETRO_AZAHAR_SUPPORTS_IN_SOURCE_BUILD = NO
LIBRETRO_AZAHAR_LICENSE = GPLv2
LIBRETRO_AZAHAR_EMULATOR_INFO = azahar.libretro.core.yml
LIBRETRO_AZAHAR_DEPENDENCIES = azahar retroarch

LIBRETRO_AZAHAR_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DAZAHAR_ENABLE_BUNDLE_TARGET=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DAZAHAR_WARNINGS_AS_ERRORS=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_LIBRETRO=ON
LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_LIBUSB=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_LTO=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_OPENAL=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_ROOM_STANDALONE=OFF -DENABLE_ROOM=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_QT=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_SCRIPTING=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_SDL2=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_TESTS=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DENABLE_WEB_SERVICE=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DUSE_DISCORD_PRESENCE=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DUSE_SYSTEM_CATCH2=ON
LIBRETRO_AZAHAR_CONF_OPTS += -DUSE_SYSTEM_FMT=OFF
LIBRETRO_AZAHAR_CONF_OPTS += -DUSE_SYSTEM_OPENAL=ON
LIBRETRO_AZAHAR_CONF_OPTS += -DUSE_SYSTEM_OPENSSL=ON

define LIBRETRO_AZAHAR_INSTALL_TARGET_CMDS
	mkdir -p $(TARGET_DIR)/usr/lib/libretro
	$(INSTALL) -D $(@D)/buildroot-build/bin/Release/azahar_libretro.so $(TARGET_DIR)/usr/lib/libretro/azahar_libretro.so
endef

$(eval $(cmake-package))
$(eval $(emulator-info-package))
