################################################################################
#
# libretro-panda3ds
#
################################################################################
# Version: Commits on Jan 18, 2026
LIBRETRO_PANDA3DS_VERSION = f5e5be4b6d8c7aa531875e5039b13fdbf3f372a8
LIBRETRO_PANDA3DS_SITE = https://github.com/wheremyfoodat/Panda3DS.git
LIBRETRO_PANDA3DS_SITE_METHOD=git
LIBRETRO_PANDA3DS_GIT_SUBMODULES=YES
LIBRETRO_PANDA3DS_SUPPORTS_IN_SOURCE_BUILD = NO
LIBRETRO_PANDA3DS_LICENSE = GPLv3
LIBRETRO_PANDA3DS_DEPENDENCIES = fdk-aac ffmpeg fmt lua

LIBRETRO_PANDA3DS_CONF_OPTS += -DCMAKE_CXX_COMPILER=$(HOST_DIR)/bin/$(GNU_TARGET_NAME)-g++
LIBRETRO_PANDA3DS_CONF_OPTS += -DBUILD_LIBRETRO_CORE=ON
LIBRETRO_PANDA3DS_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
LIBRETRO_PANDA3DS_CONF_OPTS += -DBUILD_STATIC_LIBS=ON
LIBRETRO_PANDA3DS_CONF_OPTS += -DENABLE_DISCORD_RPC=OFF
LIBRETRO_PANDA3DS_CONF_OPTS += -DENABLE_GIT_VERSIONING=OFF
LIBRETRO_PANDA3DS_CONF_OPTS += -DENABLE_LTO=ON
LIBRETRO_PANDA3DS_CONF_OPTS += -DENABLE_OPENGL=ON
LIBRETRO_PANDA3DS_CONF_OPTS += -DENABLE_RENDERDOC_API=OFF
LIBRETRO_PANDA3DS_CONF_OPTS += -DSDL_AUDIO=OFF
LIBRETRO_PANDA3DS_CONF_OPTS += -DSDL_VIDEO=OFF
LIBRETRO_PANDA3DS_CONF_OPTS += -DUSE_SYSTEM_SDL2=ON

ifeq ($(BR2_PACKAGE_BATOCERA_VULKAN),y)
    LIBRETRO_PANDA3DS_CONF_OPTS += -DENABLE_VULKAN=ON
    LIBRETRO_PANDA3DS_DEPENDENCIES += host-glslang glslang vulkan-headers
else
    LIBRETRO_PANDA3DS_CONF_OPTS += -DENABLE_VULKAN=OFF
endif

define LIBRETRO_PANDA3DS_INSTALL_TARGET_CMDS
	mkdir -p $(TARGET_DIR)/usr/lib/libretro
	$(INSTALL) -D $(@D)/buildroot-build/panda3ds_libretro.so $(TARGET_DIR)/usr/lib/libretro/panda3ds_libretro.so
	mkdir -p $(TARGET_DIR)/usr/share/libretro/info
	$(INSTALL) -D $(@D)/docs/libretro/panda3ds_libretro.info $(TARGET_DIR)/usr/share/libretro/info/
endef

$(eval $(cmake-package))
