################################################################################
#
# batocera-es-piboy
#
################################################################################
# Version: Commits on Jan 28, 2026
BATOCERA_ES_PIBOY_VERSION = f396b45b49d0a35d8dfc16ff5c5a4bfd050d2d0b
BATOCERA_ES_PIBOY_SITE = https://github.com/batocera-linux/batocera-emulationstation
BATOCERA_ES_PIBOY_SITE_METHOD = git
BATOCERA_ES_PIBOY_GIT_SUBMODULES = YES
BATOCERA_ES_PIBOY_LICENSE = MIT
BATOCERA_ES_PIBOY_DEPENDENCIES = alsa-lib batocera-es-system freetype libcurl libfreeimage pugixml rapidjson sdl2 sdl2_mixer vlc
BATOCERA_ES_PIBOY_DEPENDENCIES += host-gettext

# use gcc to build
BATOCERA_ES_PIBOY_CONF_OPTS += -DCMAKE_C_COMPILER=$(HOST_DIR)/bin/$(GNU_TARGET_NAME)-gcc
BATOCERA_ES_PIBOY_CONF_OPTS += -DCMAKE_CXX_COMPILER=$(HOST_DIR)/bin/$(GNU_TARGET_NAME)-g++
BATOCERA_ES_PIBOY_CONF_OPTS += -DCMAKE_CXX_FLAGS="$(TARGET_CFLAGS) -D$(call UPPERCASE,$(BATOCERA_SYSTEM_ARCH))"
BATOCERA_ES_PIBOY_CONF_OPTS += -DUSE_SYSTEM_PUGIXML=ON

ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_X86_64_ANY),y)
BATOCERA_ES_PIBOY_CONF_OPTS += -DGL=ON
else
ifeq ($(BR2_PACKAGE_HAS_LIBGLES),y)
BATOCERA_ES_PIBOY_CONF_OPTS += -DGLES2=ON
endif
endif

ifeq ($(BR2_PACKAGE_ESPEAK),y)
BATOCERA_ES_PIBOY_CONF_OPTS += -DENABLE_TTS=ON
BATOCERA_ES_PIBOY_DEPENDENCIES += espeak
endif

ifeq ($(BR2_PACKAGE_KODI),y)
BATOCERA_ES_PIBOY_CONF_OPTS += -DDISABLE_KODI=OFF
else
BATOCERA_ES_PIBOY_CONF_OPTS += -DDISABLE_KODI=ON
endif

ifeq ($(BR2_PACKAGE_PULSEAUDIO_ENABLE_ATOMIC),y)
BATOCERA_ES_PIBOY_CONF_OPTS += -DENABLE_PULSE=ON
else
BATOCERA_ES_PIBOY_CONF_OPTS += -DENABLE_PULSE=OFF
endif

ifeq ($(BR2_PACKAGE_XORG7),y)
BATOCERA_ES_PIBOY_CONF_OPTS += -DENABLE_FILEMANAGER=ON
else
BATOCERA_ES_PIBOY_CONF_OPTS += -DENABLE_FILEMANAGER=OFF
endif

BATOCERA_ES_PIBOY_CONF_OPTS += -DBATOCERA=ON
BATOCERA_ES_PIBOY_CONF_OPTS += -DNOUPDATE=ON
BATOCERA_ES_PIBOY_CONF_OPTS += -DPIBOY=ON

# disabling cec. causing perf issue on init/deinit
ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_RK3128),y)
    BATOCERA_ES_PIBOY_CONF_OPTS += -DCEC=OFF
else
    BATOCERA_ES_PIBOY_CONF_OPTS += -DCEC=ON
endif

BATOCERA_ES_PIBOY_KEY_SCREENSCRAPER_DEV_LOGIN=$(shell grep -E '^SCREENSCRAPER_DEV_LOGIN=' /home/lee/keys.txt | cut -d = -f 2-)
BATOCERA_ES_PIBOY_KEY_GAMESDB_APIKEY=$(shell grep -E '^GAMESDB_APIKEY=' /home/lee/keys.txt | cut -d = -f 2-)
BATOCERA_ES_PIBOY_KEY_CHEEVOS_DEV_LOGIN=$(shell grep -E '^CHEEVOS_DEV_LOGIN=' /home/lee/keys.txt | cut -d = -f 2-)
BATOCERA_ES_PIBOY_KEY_HFS_DEV_LOGIN=$(shell grep -E '^HFS_DEV_LOGIN=' /home/lee/keys.txt | cut -d = -f 2-)

ifneq ($(BATOCERA_ES_PIBOY_KEY_SCREENSCRAPER_DEV_LOGIN),)
BATOCERA_ES_PIBOY_CONF_OPTS += "-DSCREENSCRAPER_DEV_LOGIN=$(BATOCERA_ES_PIBOY_KEY_SCREENSCRAPER_DEV_LOGIN)"
endif
ifneq ($(BATOCERA_ES_PIBOY_KEY_GAMESDB_APIKEY),)
BATOCERA_ES_PIBOY_CONF_OPTS += "-DGAMESDB_APIKEY=$(BATOCERA_ES_PIBOY_KEY_GAMESDB_APIKEY)"
endif
ifneq ($(BATOCERA_ES_PIBOY_KEY_CHEEVOS_DEV_LOGIN),)
BATOCERA_ES_PIBOY_CONF_OPTS += "-DCHEEVOS_DEV_LOGIN=$(BATOCERA_ES_PIBOY_KEY_CHEEVOS_DEV_LOGIN)"
endif
ifneq ($(BATOCERA_ES_PIBOY_KEY_HFS_DEV_LOGIN),)
BATOCERA_ES_PIBOY_CONF_OPTS += "-DHFS_DEV_LOGIN=$(BATOCERA_ES_PIBOY_KEY_HFS_DEV_LOGIN)"
endif

define BATOCERA_ES_PIBOY_RPI_FIXUP
	$(SED) 's|.{CMAKE_FIND_ROOT_PATH}/opt/vc|$(STAGING_DIR)/usr|g' $(@D)/CMakeLists.txt
	$(SED) 's|.{CMAKE_FIND_ROOT_PATH}/usr|$(STAGING_DIR)/usr|g'	$(@D)/CMakeLists.txt
endef

BATOCERA_ES_PIBOY_PRE_CONFIGURE_HOOKS += BATOCERA_ES_PIBOY_RPI_FIXUP

define BATOCERA_ES_PIBOY_INSTALL_TARGET_CMDS
	$(INSTALL) -m 0755 $(@D)/emulationstation -D $(TARGET_DIR)/usr/bin/emulationstation_piboy
endef

$(eval $(cmake-package))
