################################################################################
#
# eka2l1
#
################################################################################
# Version: Commits on Feb 28, 2026
EKA2L1_VERSION = d2e7abb191bf41ffa1413100154590e0930aebfa
EKA2L1_SITE = https://github.com/AveyondFly/EKA2L1.git
EKA2L1_SITE_METHOD=git
EKA2L1_GIT_SUBMODULES=YES
EKA2L1_LICENSE = GPLv2
EKA2L1_DEPENDENCIES = sdl2
EKA2L1_EMULATOR_INFO = eka2l1.emulator.yml

EKA2L1_SUPPORTS_IN_SOURCE_BUILD = NO

EKA2L1_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
EKA2L1_CONF_OPTS += -DBUILD_STATIC_LIBS=ON
EKA2L1_CONF_OPTS += -DEKA2L1_BUILD_SDL2_FRONTEND=ON
EKA2L1_CONF_OPTS += -DEKA2L1_BUILD_TESTS=OFF
EKA2L1_CONF_OPTS += -DEKA2L1_BUILD_TOOLS=OFF
EKA2L1_CONF_OPTS += -DEKA2L1_ENABLE_SCRIPTING_ABILITY=OFF
EKA2L1_CONF_OPTS += -DEKA2L1_NO_QT_FRONTEND=ON
EKA2L1_CONF_OPTS += -DEKA2L1_USE_SYSTEM_FFMPEG=ON
EKA2L1_CONF_OPTS += -DENABLE_PROGRAMS=OFF # for mbedtls

# use gcc to build
EKA2L1_CONF_OPTS += -DCMAKE_C_COMPILER=$(HOST_DIR)/bin/$(GNU_TARGET_NAME)-gcc
EKA2L1_CONF_OPTS += -DCMAKE_CXX_COMPILER=$(HOST_DIR)/bin/$(GNU_TARGET_NAME)-g++

ifeq ($(BR2_PACKAGE_BATOCERA_WAYLAND),y)
    EKA2L1_CONF_OPTS += -DEKA2L1_UNIX_USE_X11=OFF
    EKA2L1_CONF_OPTS += -DEKA2L1_UNIX_USE_WAYLAND=ON
endif

define EKA2L1_INSTALL_TARGET_CMDS
	mkdir -p $(TARGET_DIR)/usr/bin/eka2l1
	cp -R $(@D)/buildroot-build/bin/* $(TARGET_DIR)/usr/bin/eka2l1/
endef

$(eval $(cmake-package))
$(eval $(emulator-info-package))
