################################################################################
#
# libretro-play
#
################################################################################
# Version: Commits on Jun 18, 2024
LIBRETRO_PLAY_VERSION = d0dd51a23567d271bd4a0db7e8a8c938b58b7676
LIBRETRO_PLAY_SOURCE = play-$(LIBRETRO_PLAY_VERSION)-git4.tar.gz
LIBRETRO_PLAY_SITE = https://github.com/jpd002/Play-.git
LIBRETRO_PLAY_LICENSE = BSD

LIBRETRO_PLAY_SITE_METHOD = git
LIBRETRO_PLAY_GIT_SUBMODULES = YES
LIBRETRO_PLAY_LICENSE = BSD

LIBRETRO_PLAY_CONF_OPTS += -DBUILD_STATIC_LIBS=ON
LIBRETRO_PLAY_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
LIBRETRO_PLAY_CONF_OPTS += -DBUILD_TESTS=OFF
LIBRETRO_PLAY_CONF_OPTS += -DBUILD_LIBRETRO_CORE=ON
LIBRETRO_PLAY_CONF_OPTS += -DBUILD_PLAY=OFF
LIBRETRO_PLAY_CONF_OPTS += -DENABLE_AMAZON_S3=ON

ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_X86_64_ANY),y)
LIBRETRO_PLAY_DEPENDENCIES = libglew
endif

# Force to use GLES on ARM
ifeq ($(BR2_aarch64)$(BR2_arm),y)
LIBRETRO_PLAY_CONF_OPTS += -DUSE_GLEW=OFF
LIBRETRO_PLAY_CONF_OPTS += -DUSE_GLES=ON
endif

ifeq ($(BR2_aarch64),y)
LIBRETRO_PLAY_CONF_OPTS += -DTARGET_PLATFORM_UNIX_AARCH64=YES
else ifeq ($(BR2_arm),y)
LIBRETRO_PLAY_CONF_OPTS += -DTARGET_PLATFORM_UNIX_ARM=YES
endif

$(eval $(cmake-package))
