default:
  # shader affects retroarch shaders
  shader: crt/crt-potato-cool
  # scanline affect fba2x
  scanline: false
snes:
  shader: crt/crt-potato-cool
nes:
  shader: crt/crt-potato-cool
n64:
  shader: crt/crt-potato-cool
gba:
  shader: crt/crt-potato-cool
gb:
  shader: crt/crt-potato-cool
gbc:
  shader: crt/crt-potato-cool
fds:
  shader: crt/crt-potato-cool
virtualboy:
  shader: crt/crt-potato-cool
# Sega
sg1000:
  shader: crt/crt-potato-cool
mastersystem:
  shader: crt/crt-potato-cool
megadrive:
  shader: crt/crt-potato-cool
gamegear:
  shader: crt/crt-potato-cool
sega32x:
  shader: crt/crt-potato-cool
segacd:
  shader: crt/crt-potato-cool
# Arcade
neogeo:
  shader: crt/crt-potato-cool
neogeocd:
  shader: crt/crt-potato-cool
mame:
  shader: crt/crt-potato-cool
fba:
  shader: crt/crt-potato-cool
naomi:
  shader: crt/crt-potato-cool
atomiswave:
  shader: crt/crt-potato-cool
#
ngp:
  shader: crt/crt-potato-cool
ngpc:
  shader: crt/crt-potato-cool
gw:
  shader: crt/crt-potato-cool
vectrex:
  shader:
lynx:
  shader: crt/crt-potato-cool
lutro:
  shader: crt/crt-potato-cool
wswan:
  shader: crt/crt-potato-cool
wswanc:
  shader: crt/crt-potato-cool
pcengine:
  shader: crt/crt-potato-cool
pcenginecd:
  shader: crt/crt-potato-cool
supergrafx:
  shader: crt/crt-potato-cool
atari800:
  shader: crt/crt-potato-cool
atari2600:
  shader: crt/crt-potato-cool
atari5200:
  shader: crt/crt-potato-cool
atari7800:
  shader: crt/crt-potato-cool
prboom:
  shader: crt/crt-potato-cool
psx:
  shader: crt/crt-potato-cool
colecovision:
  shader: crt/crt-potato-cool
# Computers
msx:
  shader: crt/crt-potato-cool
msx1:
  shader: crt/crt-potato-cool
msx2:
  shader: crt/crt-potato-cool
amiga:
  shader: crt/crt-potato-cool
amstradcpc:
  shader: crt/crt-potato-cool
atarist:
  shader: crt/crt-potato-cool
zxspectrum:
  shader: crt/crt-potato-cool
odyssey2:
  shader: crt/crt-potato-cool
zx81:
  shader: crt/crt-potato-cool
pcfx:
  shader: crt/crt-potato-cool
x68000:
  shader: crt/crt-potato-cool
