################################################################################
#
# libretro-scummvm-mainline
#
################################################################################
# Version: Commits on Jan 05, 2023
LIBRETRO_SCUMMVM_MAINLINE_VERSION = 5ce8142a0339ff7eda78f515b6d12d72a1732a31
LIBRETRO_SCUMMVM_MAINLINE_SITE = https://github.com/libretro/scummvm.git

LIBRETRO_SCUMMVM_MAINLINE_SITE_METHOD=git
LIBRETRO_SCUMMVM_MAINLINE_GIT_SUBMODULES=YES
LIBRETRO_SCUMMVM_MAINLINE_SUPPORTS_IN_SOURCE_BUILD = NO
LIBRETRO_SCUMMVM_MAINLINE_LICENSE = GPLv3

ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_BCM2835),y)
LIBRETRO_SCUMMVM_MAINLINE_PLATFORM = rpi1

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_BCM2836),y)
LIBRETRO_SCUMMVM_MAINLINE_PLATFORM = rpi2

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_RPIZERO2),y)
LIBRETRO_SCUMMVM_MAINLINE_PLATFORM = rpi3

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_BCM2837),y)
LIBRETRO_SCUMMVM_MAINLINE_PLATFORM = rpi3_64
LIBRETRO_SCUMMVM_MAINLINE_MAKE_OPTS += TARGET_64BIT=1

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_BCM2711),y)
LIBRETRO_SCUMMVM_MAINLINE_PLATFORM = rpi4_64
LIBRETRO_SCUMMVM_MAINLINE_MAKE_OPTS += TARGET_64BIT=1

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_S812),y)
LIBRETRO_SCUMMVM_MAINLINE_PLATFORM = armv cortexa9 neon hardfloat

else ifeq ($(BR2_aarch64),y)
LIBRETRO_SCUMMVM_MAINLINE_PLATFORM = unix
LIBRETRO_SCUMMVM_MAINLINE_MAKE_OPTS += TARGET_64BIT=1

else ifeq ($(BR2_x86_64),y)
LIBRETRO_SCUMMVM_MAINLINE_PLATFORM = unix
LIBRETRO_SCUMMVM_MAINLINE_MAKE_OPTS += TARGET_64BIT=1
endif

define LIBRETRO_SCUMMVM_MAINLINE_BUILD_CMDS
	$(TARGET_CONFIGURE_OPTS) $(MAKE) CXX="$(TARGET_CXX)" CC="$(TARGET_CC)" -C $(@D)/ -f Makefile platform="$(LIBRETRO_SCUMMVM_MAINLINE_PLATFORM)" $(LIBRETRO_SCUMMVM_MAINLINE_MAKE_OPTS)
endef

define LIBRETRO_SCUMMVM_MAINLINE_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/scummvm_libretro.so $(TARGET_DIR)/usr/lib/libretro/scummvm_libretro.so
endef

$(eval $(generic-package))
