#!/bin/sh
enabled="$(batocera-settings-get -f /boot/batocera-boot.conf key piboyxrs.enabled)"

case "$1" in
	start)
		if [[ $enabled == "1" ]]; then
			echo "Starting PiBoy XRS"
			modprobe xpi_gamecon_xrs
			touch /tmp/piboy
			cp /usr/share/batocera/configgen/configgen-defaults-piboy4.yml /usr/share/batocera/configgen/configgen-defaults-arch.yml
			dmesg -n 1
			python /usr/bin/piboy_audctrl.py &
			python /usr/bin/piboy_fan_power_ctrl.py &
			# disable LCD display if HDMI is connected
			if grep -q -E '^connected' /sys/class/drm/card?-HDMI-A-*/status; then
				echo 0 >/sys/kernel/xpi_gamecon/flags
			fi > /dev/null 2>&1
		fi
		;;
	stop)
		if [[ $enabled == "1" ]]; then
			echo "Stopping PiBoy XRS"
			rm /tmp/piboy
			kill $(ps aux | grep piboy_fan_power_ctrl | awk '{ print $1 }') > /dev/null 2>&1
			kill $(ps aux | grep volumed | awk '{ print $1 }') > /dev/null 2>&1

			# reboot requested
			if runlevel | grep -q -E '(6|unknown)$'; then
				echo "129" > /sys/kernel/xpi_gamecon/flags; sleep 1
			fi
			# shutdown requested
			if runlevel | grep -q '0$'; then
				echo "0" > /sys/kernel/xpi_gamecon/flags
				rmmod xpi_gamecon
			fi
		fi
		;;
	*)
		echo "Usage: /etc/init.d/S34piboyxrs {start|stop}"
		exit 1
	;;
esac

exit 0
