## MEGA-BEZEL
default:
  # shader affects retroarch shaders
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
  # scanline affect fba2x
  scanline: true
snes:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
nes:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
n64:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
gba:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__LCD-GRID
gb:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__LCD-GRID
gbc:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__LCD-GRID
pokemini:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__LCD-GRID
fds:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
virtualboy:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__LCD-GRID
nds:
  # shader: bezel/Mega_Bezel/Presets/Dual-Screen-DS__STD__LCD-GRID
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__LCD-GRID
3ds:
  # shader: bezel/Mega_Bezel/Presets/Dual-Screen-3DS__STD__LCD-GRID
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__LCD-GRID
# Sega
sg1000:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
mastersystem:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
megadrive:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__GENESIS
gamegear:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__LCD-GRID
sega32x:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__GENESIS
segacd:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__GENESIS
# Arcade
neogeo:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
neogeocd:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
mame:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
fba:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
naomi:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
atomiswave:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
#
ngp:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__LCD-GRID
ngpc:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__LCD-GRID
gw:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
vectrex:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
lynx:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__LCD-GRID
lutro:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
wswan:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__LCD-GRID
wswanc:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__LCD-GRID
pcengine:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
pcenginecd:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
supergrafx:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
atari800:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
atari2600:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
atari5200:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
atari7800:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
prboom:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
psx:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
psp:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__LCD-GRID
colecovision:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
# Computers
msx:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
msx1:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
msx2:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
amiga:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
amstradcpc:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
atarist:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
zxspectrum:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
odyssey2:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
zx81:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
pcfx:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
x68000:
  shader: bezel/Mega_Bezel/Presets/MBZ__4__STD-NOREFLECT__NOINTRO
