################################################################################
#
# gamenetworkingsockets
#
################################################################################
# Version: Commits on Apr 18, 2026
GAMENETWORKINGSOCKETS_VERSION = 7067b9a3b91eb3d2d501d1e4d984299aff1a3bb3
GAMENETWORKINGSOCKETS_SITE = https://github.com/ValveSoftware/GameNetworkingSockets
GAMENETWORKINGSOCKETS_SITE_METHOD = git
GAMENETWORKINGSOCKETS_GIT_SUBMODULES = YES
GAMENETWORKINGSOCKETS_SUPPORTS_IN_SOURCE_BUILD = NO
GAMENETWORKINGSOCKETS_LICENSE = BSD-3-Clause license
GAMENETWORKINGSOCKETS_LICENSE_FILES = LICENSE
GAMENETWORKINGSOCKETS_INSTALL_STAGING = YES

GAMENETWORKINGSOCKETS_DEPENDENCIES = openssl protobuf

GAMENETWORKINGSOCKETS_CONF_OPTS += -DCMAKE_C_COMPILER=$(HOST_DIR)/bin/$(GNU_TARGET_NAME)-gcc
GAMENETWORKINGSOCKETS_CONF_OPTS += -DCMAKE_CXX_COMPILER=$(HOST_DIR)/bin/$(GNU_TARGET_NAME)-g++

$(eval $(cmake-package))
