################################################################################
#
# gamenetworkingsockets
#
################################################################################
# Version: Commits on Aug 05, 2026
GAMENETWORKINGSOCKETS_VERSION = e707b3a6b638f4de31ee3e13a64284bd9abfa98e
GAMENETWORKINGSOCKETS_SITE = https://github.com/ValveSoftware/GameNetworkingSockets
GAMENETWORKINGSOCKETS_SITE_METHOD = git
GAMENETWORKINGSOCKETS_GIT_SUBMODULES = YES
GAMENETWORKINGSOCKETS_SUPPORTS_IN_SOURCE_BUILD = NO
GAMENETWORKINGSOCKETS_LICENSE = BSD-3-Clause license
GAMENETWORKINGSOCKETS_LICENSE_FILES = LICENSE
GAMENETWORKINGSOCKETS_INSTALL_STAGING = YES

GAMENETWORKINGSOCKETS_DEPENDENCIES = openssl protobuf

GAMENETWORKINGSOCKETS_CONF_OPTS += -DCMAKE_C_COMPILER=$(HOST_DIR)/bin/$(GNU_TARGET_NAME)-gcc
GAMENETWORKINGSOCKETS_CONF_OPTS += -DCMAKE_CXX_COMPILER=$(HOST_DIR)/bin/$(GNU_TARGET_NAME)-g++

$(eval $(cmake-package))
