################################################################################
#
# libretro-flycast2022
#
################################################################################
# Version: Commits on Apr 09, 2022
LIBRETRO_FLYCAST2022_VERSION = v1.3
LIBRETRO_FLYCAST2022_SITE = https://github.com/flyinghead/flycast.git
LIBRETRO_FLYCAST2022_SITE_METHOD=git
LIBRETRO_FLYCAST2022_GIT_SUBMODULES=YES
LIBRETRO_FLYCAST2022_LICENSE = GPLv2
LIBRETRO_FLYCAST2022_DEPENDENCIES = retroarch

LIBRETRO_FLYCAST2022_PLATFORM = $(LIBRETRO_PLATFORM)

LIBRETRO_FLYCAST2022_CONF_OPTS = -DCMAKE_BUILD_TYPE=Release -DUSE_OPENMP=ON \
	-DLIBRETRO=ON -DBUILD_SHARED_LIBS=OFF \
	-DBUILD_EXTERNAL=ON -DWITH_SYSTEM_ZLIB=ON \
    -DGIT_VERSION="$(shell echo $(LIBRETRO_FLYCAST2022_VERSION) | cut -c 1-7)"

ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_X86_64_ANY),y)
    LIBRETRO_FLYCAST2022_CONF_OPTS += -DUSE_OPENGL=ON
else ifeq ($(BR2_PACKAGE_BATOCERA_GLES3),y)
    LIBRETRO_FLYCAST2022_CONF_OPTS += -DUSE_GLES2=ON -DUSE_GLES=OFF
else ifeq ($(BR2_PACKAGE_BATOCERA_GLES2),y)
    LIBRETRO_FLYCAST2022_CONF_OPTS += -DUSE_GLES2=ON -DUSE_GLES=OFF
endif

ifeq ($(BR2_PACKAGE_BATOCERA_VULKAN),y)
    LIBRETRO_FLYCAST2022_CONF_OPTS += -DUSE_VULKAN=ON
else
    LIBRETRO_FLYCAST2022_CONF_OPTS += -DUSE_VULKAN=OFF
endif

# RPI: use the legacy Broadcom GLES libraries
ifeq ($(BR2_PACKAGE_BATOCERA_RPI_VCORE),y)
    LIBRETRO_FLYCAST2022_CONF_OPTS += -DUSE_VIDEOCORE=ON
endif

ifeq ($(BR2_PACKAGE_HAS_LIBMALI),y)
    LIBRETRO_FLYCAST2022_CONF_OPTS += -DUSE_MALI=ON
endif

ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_RG552),y)
    LIBRETRO_FLYCAST2022_CONF_OPTS += -DRG552=ON
else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_BCM2711),y)
    LIBRETRO_FLYCAST2022_CONF_OPTS += -DRPI4=ON
else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_RK3326),y)
    LIBRETRO_FLYCAST2022_CONF_OPTS += -DRK3326=ON
else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_S922X),y)
    LIBRETRO_FLYCAST2022_CONF_OPTS += -DS922X=ON
endif

define LIBRETRO_FLYCAST2022_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/flycast_libretro.so \
		$(TARGET_DIR)/usr/lib/libretro/flycast2022_libretro.so
endef

$(eval $(cmake-package))
