################################################################################
#
# spirv-cross
#
################################################################################
NULL-NULL
SPIRV_CROSS_VERSION =
SPIRV_CROSS_BRANCH = vulkan-sdk-1.4.328
SPIRV_CROSS_SITE = $(call github,KhronosGroup,SPIRV-Cross,$(SPIRV_CROSS_VERSION))
SPIRV_CROSS_LICENSE = Apache-2.0
SPIRV_CROSS_LICENSE_FILES = LICENSE
SPIRV_CROSS_DEPENDENCIES = spirv-headers
SPIRV_CROSS_INSTALL_STAGING = YES

SPIRV_CROSS_CONF_OPTS += -DSPIRV_CROSS_SHARED=ON
SPIRV_CROSS_CONF_OPTS += -DSPIRV_CROSS_STATIC=OFF
SPIRV_CROSS_CONF_OPTS += -DSPIRV_CROSS_CLI=OFF
SPIRV_CROSS_CONF_OPTS += -DSPIRV_CROSS_ENABLE_TESTS=OFF
SPIRV_CROSS_CONF_OPTS += -DSPIRV_CROSS_ENABLE_GLSL=ON
SPIRV_CROSS_CONF_OPTS += -DSPIRV_CROSS_ENABLE_HLSL=OFF
SPIRV_CROSS_CONF_OPTS += -DSPIRV_CROSS_ENABLE_MSL=OFF
SPIRV_CROSS_CONF_OPTS += -DSPIRV_CROSS_ENABLE_CPP=OFF
SPIRV_CROSS_CONF_OPTS += -DSPIRV_CROSS_ENABLE_REFLECT=OFF
SPIRV_CROSS_CONF_OPTS += -DSPIRV_CROSS_ENABLE_C_API=ON
SPIRV_CROSS_CONF_OPTS += -DSPIRV_CROSS_ENABLE_UTIL=ON

HOST_SPIRV_CROSS_DEPENDENCIES = spirv-headers
HOST_SPIRV_CROSS_CONF_OPTS += -DSPIRV_CROSS_SHARED=ON
HOST_SPIRV_CROSS_CONF_OPTS += -DSPIRV_CROSS_STATIC=OFF
HOST_SPIRV_CROSS_CONF_OPTS += -DSPIRV_CROSS_CLI=OFF
HOST_SPIRV_CROSS_CONF_OPTS += -DSPIRV_CROSS_ENABLE_TESTS=OFF
HOST_SPIRV_CROSS_CONF_OPTS += -DSPIRV_CROSS_ENABLE_GLSL=ON
HOST_SPIRV_CROSS_CONF_OPTS += -DSPIRV_CROSS_ENABLE_HLSL=OFF
HOST_SPIRV_CROSS_CONF_OPTS += -DSPIRV_CROSS_ENABLE_MSL=OFF
HOST_SPIRV_CROSS_CONF_OPTS += -DSPIRV_CROSS_ENABLE_CPP=OFF
HOST_SPIRV_CROSS_CONF_OPTS += -DSPIRV_CROSS_ENABLE_REFLECT=OFF
HOST_SPIRV_CROSS_CONF_OPTS += -DSPIRV_CROSS_ENABLE_C_API=ON
HOST_SPIRV_CROSS_CONF_OPTS += -DSPIRV_CROSS_ENABLE_UTIL=ON

$(eval $(cmake-package))
$(eval $(host-cmake-package))
