default:
  # shader affects retroarch shaders
  shader: anti-aliasing/aa-shader-4.0
  # scanline affect fba2x
  scanline: false
snes:
  shader: anti-aliasing/aa-shader-4.0
nes:
  shader: anti-aliasing/aa-shader-4.0
n64:
  shader: anti-aliasing/aa-shader-4.0
gba:
  shader: handheld/zfast-lcd
gb:
  shader: handheld/zfast-lcd
gbc:
  shader: handheld/zfast-lcd
fds:
  shader: handheld/zfast-lcd
virtualboy:
  shader: handheld/zfast-lcd
# Sega
sg1000:
  shader: anti-aliasing/aa-shader-4.0
mastersystem:
  shader: anti-aliasing/aa-shader-4.0
megadrive:
  shader: anti-aliasing/aa-shader-4.0
gamegear:
  shader: handheld/zfast-lcd
sega32x:
  shader: anti-aliasing/aa-shader-4.0
segacd:
  shader: anti-aliasing/aa-shader-4.0
# Arcade
neogeo:
  shader: xbr/super-xbr-2p-small-details
neogeocd:
  shader: xbr/super-xbr-2p-small-details
mame:
  shader: xbr/super-xbr-2p-small-details
fba:
  shader: xbr/super-xbr-2p-small-details
naomi:
  shader: xbr/super-xbr-2p-small-details
atomiswave:
  shader: xbr/super-xbr-2p-small-details
#
ngp:
  shader: handheld/zfast-lcd
ngpc:
  shader: handheld/zfast-lcd
gw:
  shader: anti-aliasing/aa-shader-4.0
vectrex:
  shader: handheld/zfast-lcd
lynx:
  shader: handheld/zfast-lcd
lutro:
  shader: anti-aliasing/aa-shader-4.0
wswan:
  shader: handheld/zfast-lcd
wswanc:
  shader: handheld/zfast-lcd
pcengine:
  shader: anti-aliasing/aa-shader-4.0
pcenginecd:
  shader: anti-aliasing/aa-shader-4.0
supergrafx:
  shader: anti-aliasing/aa-shader-4.0
atari800:
  shader: anti-aliasing/aa-shader-4.0
atari2600:
  shader: anti-aliasing/aa-shader-4.0
atari5200:
  shader: anti-aliasing/aa-shader-4.0
atari7800:
  shader: anti-aliasing/aa-shader-4.0
prboom:
  shader: anti-aliasing/aa-shader-4.0
psx:
  shader: xbr/super-xbr-2p-small-details
colecovision:
  shader: anti-aliasing/aa-shader-4.0
# Computers
msx:
  shader: anti-aliasing/aa-shader-4.0
msx1:
  shader: anti-aliasing/aa-shader-4.0
msx2:
  shader: anti-aliasing/aa-shader-4.0
amiga:
  shader: anti-aliasing/aa-shader-4.0
amstradcpc:
  shader: anti-aliasing/aa-shader-4.0
atarist:
  shader: anti-aliasing/aa-shader-4.0
zxspectrum:
  shader: anti-aliasing/aa-shader-4.0
odyssey2:
  shader: anti-aliasing/aa-shader-4.0
zx81:
  shader: anti-aliasing/aa-shader-4.0
pcfx:
  shader: anti-aliasing/aa-shader-4.0
x68000:
  shader: anti-aliasing/aa-shader-4.0
