#!/bin/bash
clear
echo '--------------------------------------------------------'
echo
echo 'You are about to update the Raspberry Pi4 Firmware'
echo 'This can be Dangerous and could potentially brick your'
echo 'RPI if not done correctly'
echo 
echo 'Please enusre your RPI is connected to AC power before'
echo 'proceeding with the update process.'
echo
echo '--------------------------------------------------------'
read -p "Do you want to proceed? (yes/no)" yn

case $yn in 
	yes ) echo Proceeding with the firmware update, please wait...;;
	no ) echo NOT applying Firmware update
		exit;;
	* ) echo NOT applying Firmware update
		exit 1;;
esac
mount -o remount,rw /boot
/usr/bin/rpi-eeprom-update -a
#rpi-eeprom-digest -i /lib/firmware/raspberrypi/bootloader/default/pieeprom-2022-11-04.bin -o /boot/pieeprom.sig
#cp /lib/firmware/raspberrypi/bootloader/default/pieeprom-2022-11-04.bin /boot/pieeprom.upd
#chmod -f go+r /boot/pieeprom.upd /boot/pieeprom.sig
#echo 'Please reboot your Raspberry Pi4'