################################################################################
#
# libretro-citra
#
################################################################################
# Version: Commits on Feb 13, 2026
LIBRETRO_CITRA_VERSION = b462d50d7eec6841ebd6453a53882042b6a50e67
LIBRETRO_CITRA_SITE = https://github.com/warmenhoven/azahar.git
LIBRETRO_CITRA_BRANCH = warmenhoven/dev/azahar_libretro
LIBRETRO_CITRA_SITE_METHOD=git
LIBRETRO_CITRA_GIT_SUBMODULES=YES
LIBRETRO_CITRA_SUPPORTS_IN_SOURCE_BUILD = NO
LIBRETRO_CITRA_LICENSE = GPLv2
LIBRETRO_CITRA_EMULATOR_INFO = citra.libretro.core.yml
LIBRETRO_CITRA_DEPENDENCIES = azahar retroarch

LIBRETRO_CITRA_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
LIBRETRO_CITRA_CONF_OPTS += -DCITRA_ENABLE_BUNDLE_TARGET=OFF
LIBRETRO_CITRA_CONF_OPTS += -DCITRA_WARNINGS_AS_ERRORS=OFF
LIBRETRO_CITRA_CONF_OPTS += -DENABLE_LIBRETRO=ON
LIBRETRO_CITRA_CONF_OPTS += -DENABLE_LIBUSB=OFF
LIBRETRO_CITRA_CONF_OPTS += -DENABLE_LTO=OFF
LIBRETRO_CITRA_CONF_OPTS += -DENABLE_OPENAL=OFF
LIBRETRO_CITRA_CONF_OPTS += -DENABLE_ROOM_STANDALONE=OFF ENABLE_ROOM=OFF
LIBRETRO_CITRA_CONF_OPTS += -DENABLE_QT=OFF
LIBRETRO_CITRA_CONF_OPTS += -DENABLE_SCRIPTING=OFF
LIBRETRO_CITRA_CONF_OPTS += -DENABLE_SDL2=OFF
LIBRETRO_CITRA_CONF_OPTS += -DENABLE_TESTS=OFF
LIBRETRO_CITRA_CONF_OPTS += -DENABLE_WEB_SERVICE=OFF
LIBRETRO_CITRA_CONF_OPTS += -DUSE_DISCORD_PRESENCE=OFF
LIBRETRO_CITRA_CONF_OPTS += -DUSE_SYSTEM_CATCH2=ON
LIBRETRO_CITRA_CONF_OPTS += -DUSE_SYSTEM_FMT=OFF
LIBRETRO_CITRA_CONF_OPTS += -DUSE_SYSTEM_OPENAL=ON
LIBRETRO_CITRA_CONF_OPTS += -DUSE_SYSTEM_OPENSSL=ON

define LIBRETRO_CITRA_INSTALL_TARGET_CMDS
	mkdir -p $(TARGET_DIR)/usr/lib/libretro
	$(INSTALL) -D $(@D)/buildroot-build/bin/Release/azahar_libretro.so $(TARGET_DIR)/usr/lib/libretro/citra_libretro.so
endef

$(eval $(cmake-package))
$(eval $(emulator-info-package))
