################################################################################
#
# libretro-citra
#
################################################################################
# Version: Commits on Aug 17, 2025
LIBRETRO_CITRA_VERSION = 5263fae3344e5e9af43036e0e38bec2d10fb2407
LIBRETRO_CITRA_SITE = https://github.com/libretro/citra.git
LIBRETRO_CITRA_SITE_METHOD=git
LIBRETRO_CITRA_GIT_SUBMODULES=YES
LIBRETRO_CITRA_SUPPORTS_IN_SOURCE_BUILD = NO
LIBRETRO_CITRA_LICENSE = GPLv2
LIBRETRO_CITRA_DEPENDENCIES = azahar retroarch

LIBRETRO_CITRA_CONF_OPTS += -DCMAKE_CXX_COMPILER=$(HOST_DIR)/bin/$(GNU_TARGET_NAME)-g++
LIBRETRO_CITRA_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
LIBRETRO_CITRA_CONF_OPTS += -DCITRA_ENABLE_BUNDLE_TARGET=OFF
LIBRETRO_CITRA_CONF_OPTS += -DCITRA_WARNINGS_AS_ERRORS=OFF
LIBRETRO_CITRA_CONF_OPTS += -DENABLE_LIBUSB=OFF
LIBRETRO_CITRA_CONF_OPTS += -DENABLE_LTO=OFF
LIBRETRO_CITRA_CONF_OPTS += -DENABLE_OPENAL=OFF
LIBRETRO_CITRA_CONF_OPTS += -DENABLE_QT=OFF
LIBRETRO_CITRA_CONF_OPTS += -DENABLE_SCRIPTING=OFF
LIBRETRO_CITRA_CONF_OPTS += -DENABLE_SDL2=OFF
LIBRETRO_CITRA_CONF_OPTS += -DENABLE_TESTS=OFF
LIBRETRO_CITRA_CONF_OPTS += -DENABLE_WEB_SERVICE=OFF
LIBRETRO_CITRA_CONF_OPTS += -DUSE_DISCORD_PRESENCE=OFF
LIBRETRO_CITRA_CONF_OPTS += -DUSE_SYSTEM_CATCH2=ON
LIBRETRO_CITRA_CONF_OPTS += -DUSE_SYSTEM_FMT=OFF
LIBRETRO_CITRA_CONF_OPTS += -DUSE_SYSTEM_OPENAL=ON
LIBRETRO_CITRA_CONF_OPTS += -DUSE_SYSTEM_OPENSSL=ON

define LIBRETRO_CITRA_INSTALL_TARGET_CMDS
	mkdir -p $(TARGET_DIR)/usr/lib/libretro
	$(INSTALL) -D $(@D)/buildroot-build/citra_libretro.so $(TARGET_DIR)/usr/lib/libretro/citra_libretro.so
endef

$(eval $(cmake-package))
