################################################################################
#
# libretro-citra
#
################################################################################
# Version: Commits on Dec 28, 2023 (branch@vulkan)
LIBRETRO_CITRA_VERSION = 6cf80643e6bd76c9ab3d667b013fc19d307bfd30
LIBRETRO_CITRA_SITE = https://github.com/zorn-v/citra-libretro.git
LIBRETRO_CITRA_SITE_METHOD=git
LIBRETRO_CITRA_GIT_SUBMODULES=YES
LIBRETRO_CITRA_LICENSE = GPLv2
LIBRETRO_CITRA_DEPENDENCIES += fdk-aac ffmpeg fmt libbacktrace
LIBRETRO_CITRA_SUPPORTS_IN_SOURCE_BUILD = NO

LIBRETRO_CITRA_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
LIBRETRO_CITRA_CONF_OPTS += -DCITRA_ENABLE_BUNDLE_TARGET=OFF
LIBRETRO_CITRA_CONF_OPTS += -DCITRA_WARNINGS_AS_ERRORS=OFF
LIBRETRO_CITRA_CONF_OPTS += -DENABLE_LIBUSB=OFF
LIBRETRO_CITRA_CONF_OPTS += -DENABLE_LTO=OFF
LIBRETRO_CITRA_CONF_OPTS += -DENABLE_OPENAL=OFF
LIBRETRO_CITRA_CONF_OPTS += -DENABLE_QT=OFF
LIBRETRO_CITRA_CONF_OPTS += -DENABLE_SCRIPTING=OFF
LIBRETRO_CITRA_CONF_OPTS += -DENABLE_SDL2=OFF
LIBRETRO_CITRA_CONF_OPTS += -DENABLE_TESTS=OFF
LIBRETRO_CITRA_CONF_OPTS += -DENABLE_WEB_SERVICE=OFF
LIBRETRO_CITRA_CONF_OPTS += -DUSE_DISCORD_PRESENCE=OFF
LIBRETRO_CITRA_CONF_OPTS += -DUSE_SYSTEM_FMT=ON
LIBRETRO_CITRA_CONF_OPTS += -DUSE_SYSTEM_OPENSSL=ON

define LIBRETRO_CITRA_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/buildroot-build/citra_libretro.so $(TARGET_DIR)/usr/lib/libretro/citra_libretro.so
endef

$(eval $(cmake-package))
