## MEGA-BEZEL
default:
  # shader affects retroarch shaders
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
  # scanline affect fba2x
  scanline: true
snes:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
nes:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
n64:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
gba:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LCD-GRID
gb:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LCD-GRID
gbc:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LCD-GRID
pokemini:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LCD-GRID
fds:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
virtualboy:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LCD-GRID
nds:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__NDS
3ds:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__3DS
# Sega
sg1000:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
mastersystem:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
megadrive:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
gamegear:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LCD-GRID
sega32x:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
segacd:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
# Arcade
neogeo:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
neogeocd:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
mame:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
fba:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
naomi:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
atomiswave:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
#
ngp:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LCD-GRID
ngpc:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LCD-GRID
gw:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
vectrex:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
lynx:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LCD-GRID
lutro:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
wswan:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LCD-GRID
wswanc:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LCD-GRID
pcengine:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
pcenginecd:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
supergrafx:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
atari800:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
atari2600:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
atari5200:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
atari7800:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
prboom:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
psx:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
psp:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ__LCD-GRID
colecovision:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
# Computers
msx:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
msx1:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
msx2:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
amiga:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
amstradcpc:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
atarist:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
zxspectrum:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
odyssey2:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
zx81:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
pcfx:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
x68000:
  shader: bezel/Mega_Bezel/Presets/BATOCERA__MBZ
