################################################################################
#
# libretro-flycast2021
#
################################################################################
# Version: Commits on Jul 04, 2025
LIBRETRO_FLYCAST2021_VERSION = 2495c1e8c473c92c1f584252156b9ed6acd5fe8e
LIBRETRO_FLYCAST2021_SITE = $(call github,metallic77,flycast,$(LIBRETRO_FLYCAST2021_VERSION))
LIBRETRO_FLYCAST2021_LICENSE = GPLv2

LIBRETRO_FLYCAST2021_PLATFORM = $(LIBRETRO_PLATFORM)
LIBRETRO_FLYCAST2021_EXTRA_ARGS = HAVE_OPENMP=1 LDFLAGS=-lrt

ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_BCM2711),y)
    LIBRETRO_FLYCAST2021_PLATFORM = rpi4_64
    LIBRETRO_FLYCAST2021_EXTRA_ARGS += FORCE_GLES=1 ARCH=arm64

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_BCM2712),y)
    LIBRETRO_FLYCAST2021_PLATFORM = rpi5_64
    LIBRETRO_FLYCAST2021_EXTRA_ARGS += FORCE_GLES=1 ARCH=arm64

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_BCM2837),y)
    LIBRETRO_FLYCAST2021_PLATFORM = rpi3_64
    LIBRETRO_FLYCAST2021_EXTRA_ARGS += FORCE_GLES=1 ARCH=arm64

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_BCM2836),y)
    LIBRETRO_FLYCAST2021_PLATFORM = rpi2
    LIBRETRO_FLYCAST2021_EXTRA_ARGS += FORCE_GLES=1 ARCH=arm

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_RK3326),y)
    LIBRETRO_FLYCAST2021_PLATFORM = RK3326
    LIBRETRO_FLYCAST2021_EXTRA_ARGS += FORCE_GLES=1 ARCH=arm64

else ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_H3),y)
    LIBRETRO_FLYCAST2021_PLATFORM = sun8i
    LIBRETRO_FLYCAST2021_EXTRA_ARGS += FORCE_GLES=1 ARCH=arm
endif

define LIBRETRO_FLYCAST2021_BUILD_CMDS
	$(SED) "s|\-O[23]|$(TARGET_OPTIMIZATION)|g" $(@D)/Makefile
	$(TARGET_CONFIGURE_OPTS) $(MAKE) CXX="$(TARGET_CXX)" CC="$(TARGET_CC)" -C $(@D)/ -f Makefile \
		platform="$(LIBRETRO_FLYCAST2021_PLATFORM)" $(LIBRETRO_FLYCAST2021_EXTRA_ARGS) \
	GIT_VERSION="-$(shell echo $(LIBRETRO_FLYCAST2021_VERSION) | cut -c 1-7)"
endef

define LIBRETRO_FLYCAST2021_INSTALL_TARGET_CMDS
	mkdir -p $(TARGET_DIR)/usr/lib/libretro
	$(INSTALL) -D $(@D)/flycast_libretro.so $(TARGET_DIR)/usr/lib/libretro/flycast2021_libretro.so
endef

$(eval $(generic-package))
