################################################################################
#
# rpcs3
#
################################################################################
# Version: Commits on Dec 07, 2025
RPCS3_VERSION = 01fe12483f2c0c7b4b32ce427e9eb7d31c265565
RPCS3_SITE = https://github.com/RPCS3/rpcs3.git
RPCS3_SITE_METHOD=git
RPCS3_GIT_SUBMODULES=YES
RPCS3_LICENSE = GPLv2
RPCS3_DEPENDENCIES += alsa-lib cubeb ffmpeg flatbuffers libcurl libevdev libglew libglu libpng
RPCS3_DEPENDENCIES += libusb libxml2 llvm mesa3d ncurses openal opencv4 pugixml rtmpdump sdl3 wolfssl
RPCS3_DEPENDENCIES += qt6base qt6multimedia qt6svg

RPCS3_SUPPORTS_IN_SOURCE_BUILD = NO

RPCS3_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
RPCS3_CONF_OPTS += -DCMAKE_CROSSCOMPILING=ON
RPCS3_CONF_OPTS += -DCMAKE_EXE_LINKER_FLAGS="-lstdc++ -flto"
RPCS3_CONF_OPTS += -DCMAKE_INSTALL_PREFIX=/usr
RPCS3_CONF_OPTS += -DLLVM_DIR=$(STAGING_DIR)/usr/lib/cmake/llvm/
RPCS3_CONF_OPTS += -DSTATIC_LINK_LLVM=OFF
RPCS3_CONF_OPTS += -DOpenGL_GL_PREFERENCE=LEGACY
RPCS3_CONF_OPTS += -DUSE_DISCORD_RPC=OFF
RPCS3_CONF_OPTS += -DUSE_LIBEVDEV=ON
RPCS3_CONF_OPTS += -DUSE_LTO=ON
RPCS3_CONF_OPTS += -DUSE_NATIVE_INSTRUCTIONS=OFF
RPCS3_CONF_OPTS += -DUSE_PRECOMPILED_HEADERS=OFF
RPCS3_CONF_OPTS += -DUSE_SDL=ON
RPCS3_CONF_OPTS += -DUSE_SYSTEM_CUBEB=ON
RPCS3_CONF_OPTS += -DUSE_SYSTEM_CURL=ON
RPCS3_CONF_OPTS += -DUSE_SYSTEM_FFMPEG=ON
RPCS3_CONF_OPTS += -DUSE_SYSTEM_LIBPNG=ON
RPCS3_CONF_OPTS += -DUSE_SYSTEM_LIBUSB=ON
RPCS3_CONF_OPTS += -DUSE_SYSTEM_OPENCV=ON
RPCS3_CONF_OPTS += -DUSE_SYSTEM_PUGIXML=ON
RPCS3_CONF_OPTS += -DUSE_SYSTEM_RTMIDI=ON
RPCS3_CONF_OPTS += -DUSE_SYSTEM_SDL=ON
RPCS3_CONF_OPTS += -DUSE_SYSTEM_ZLIB=ON
RPCS3_CONF_OPTS += -DUSE_SYSTEM_ZSTD=ON

ifeq ($(BR2_PACKAGE_BATOCERA_VULKAN),y)
    RPCS3_CONF_OPTS += -DUSE_VULKAN=ON
else
    RPCS3_CONF_OPTS += -DUSE_VULKAN=OFF
endif

define RPCS3_VER_STRING
	$(SED) 's:$${CMAKE_SOURCE_DIR}:$(DL_DIR)/$(RPCS3_DL_SUBDIR)/git:g' $(@D)/rpcs3/git-version.cmake
endef

RPCS3_PRE_PATCH_HOOKS += RPCS3_VER_STRING

$(eval $(cmake-package))
